"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .criblcontrolplaneerror import CriblControlPlaneError
from typing import TYPE_CHECKING

from cribl_control_plane.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .apierror import APIError
    from .error import Error, ErrorData
    from .healthserverstatus_error import (
        HealthServerStatusError,
        HealthServerStatusErrorData,
    )
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError

__all__ = [
    "APIError",
    "CriblControlPlaneError",
    "Error",
    "ErrorData",
    "HealthServerStatusError",
    "HealthServerStatusErrorData",
    "NoResponseError",
    "ResponseValidationError",
]

_dynamic_imports: dict[str, str] = {
    "APIError": ".apierror",
    "Error": ".error",
    "ErrorData": ".error",
    "HealthServerStatusError": ".healthserverstatus_error",
    "HealthServerStatusErrorData": ".healthserverstatus_error",
    "NoResponseError": ".no_response_error",
    "ResponseValidationError": ".responsevalidationerror",
}


def __getattr__(attr_name: str) -> object:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
