"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "cribl-control-plane"
__version__: str = "0.7.0b14"
__openapi_doc_version__: str = "4.18.0-alpha.1775170966326-072f2c38"
__gen_version__: str = "2.873.1"
__user_agent__: str = "speakeasy-sdk/python 0.7.0b14 2.873.1 4.18.0-alpha.1775170966326-072f2c38 cribl-control-plane"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
