"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "cribl-control-plane"
__version__: str = "0.6.0b46"
__openapi_doc_version__: str = "4.17.0-alpha.1771954403808-f0bcc9c7"
__gen_version__: str = "2.839.0"
__user_agent__: str = "speakeasy-sdk/python 0.6.0b46 2.839.0 4.17.0-alpha.1771954403808-f0bcc9c7 cribl-control-plane"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
