"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "cribl-control-plane"
__version__: str = "0.10.0"
__openapi_doc_version__: str = "4.19.0-0fbd6d34"
__gen_version__: str = "2.916.4"
__user_agent__: str = (
    "speakeasy-sdk/python 0.10.0 2.916.4 4.19.0-0fbd6d34 cribl-control-plane"
)

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
