"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from cribl_control_plane import errors, models, utils
from cribl_control_plane._hooks import HookContext
from cribl_control_plane.types import OptionalNullable, UNSET
from cribl_control_plane.utils import get_security_from_env
from cribl_control_plane.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Mapping, Optional, Union


class Cribl(BaseSDK):
    def list(
        self,
        *,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.CountedSystemSettingsConf:
        r"""Get Cribl system settings

        Get Cribl system settings

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        req = self._build_request(
            method="GET",
            path="/system/settings/conf",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getSystemSettingsConf",
                oauth2_scopes=[],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.CountedSystemSettingsConf, http_res)
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(errors.ErrorData, http_res)
            raise errors.Error(response_data, http_res)
        if utils.match_response(http_res, ["401", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    async def list_async(
        self,
        *,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.CountedSystemSettingsConf:
        r"""Get Cribl system settings

        Get Cribl system settings

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        req = self._build_request_async(
            method="GET",
            path="/system/settings/conf",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getSystemSettingsConf",
                oauth2_scopes=[],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.CountedSystemSettingsConf, http_res)
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(errors.ErrorData, http_res)
            raise errors.Error(response_data, http_res)
        if utils.match_response(http_res, ["401", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    def update(
        self,
        *,
        api: Union[models.SystemSettingsConfAPI, models.SystemSettingsConfAPITypedDict],
        pii: Union[models.SystemSettingsConfPii, models.SystemSettingsConfPiiTypedDict],
        proxy: Union[
            models.SystemSettingsConfProxy, models.SystemSettingsConfProxyTypedDict
        ],
        system: Union[
            models.SystemSettingsConfSystem, models.SystemSettingsConfSystemTypedDict
        ],
        upgrade_group_settings: Union[
            models.UpgradeGroupSettings, models.UpgradeGroupSettingsTypedDict
        ],
        workers: Union[
            models.SystemSettingsConfWorkers, models.SystemSettingsConfWorkersTypedDict
        ],
        backups: Optional[
            Union[
                models.SystemSettingsConfBackups,
                models.SystemSettingsConfBackupsTypedDict,
            ]
        ] = None,
        custom_logo: Optional[
            Union[
                models.SystemSettingsConfCustomLogo,
                models.SystemSettingsConfCustomLogoTypedDict,
            ]
        ] = None,
        rollback: Optional[
            Union[
                models.SystemSettingsConfRollback,
                models.SystemSettingsConfRollbackTypedDict,
            ]
        ] = None,
        shutdown: Optional[
            Union[
                models.SystemSettingsConfShutdown,
                models.SystemSettingsConfShutdownTypedDict,
            ]
        ] = None,
        sni: Optional[
            Union[models.SystemSettingsConfSni, models.SystemSettingsConfSniTypedDict]
        ] = None,
        sockets: Optional[
            Union[
                models.SystemSettingsConfSockets,
                models.SystemSettingsConfSocketsTypedDict,
            ]
        ] = None,
        support: Optional[
            Union[
                models.SystemSettingsConfSupport,
                models.SystemSettingsConfSupportTypedDict,
            ]
        ] = None,
        tls: Optional[
            Union[models.SystemSettingsConfTLS, models.SystemSettingsConfTLSTypedDict]
        ] = None,
        upgrade_settings: Optional[
            Union[models.UpgradeSettings, models.UpgradeSettingsTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.CountedSystemSettings:
        r"""Update Cribl system settings

        Update Cribl system settings

        :param api:
        :param pii:
        :param proxy:
        :param system:
        :param upgrade_group_settings:
        :param workers:
        :param backups:
        :param custom_logo:
        :param rollback:
        :param shutdown:
        :param sni:
        :param sockets:
        :param support:
        :param tls:
        :param upgrade_settings:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.SystemSettingsConf(
            api=utils.get_pydantic_model(api, models.SystemSettingsConfAPI),
            backups=utils.get_pydantic_model(
                backups, Optional[models.SystemSettingsConfBackups]
            ),
            custom_logo=utils.get_pydantic_model(
                custom_logo, Optional[models.SystemSettingsConfCustomLogo]
            ),
            pii=utils.get_pydantic_model(pii, models.SystemSettingsConfPii),
            proxy=utils.get_pydantic_model(proxy, models.SystemSettingsConfProxy),
            rollback=utils.get_pydantic_model(
                rollback, Optional[models.SystemSettingsConfRollback]
            ),
            shutdown=utils.get_pydantic_model(
                shutdown, Optional[models.SystemSettingsConfShutdown]
            ),
            sni=utils.get_pydantic_model(sni, Optional[models.SystemSettingsConfSni]),
            sockets=utils.get_pydantic_model(
                sockets, Optional[models.SystemSettingsConfSockets]
            ),
            support=utils.get_pydantic_model(
                support, Optional[models.SystemSettingsConfSupport]
            ),
            system=utils.get_pydantic_model(system, models.SystemSettingsConfSystem),
            tls=utils.get_pydantic_model(tls, Optional[models.SystemSettingsConfTLS]),
            upgrade_group_settings=utils.get_pydantic_model(
                upgrade_group_settings, models.UpgradeGroupSettings
            ),
            upgrade_settings=utils.get_pydantic_model(
                upgrade_settings, Optional[models.UpgradeSettings]
            ),
            workers=utils.get_pydantic_model(workers, models.SystemSettingsConfWorkers),
        )

        req = self._build_request(
            method="PATCH",
            path="/system/settings/conf",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.SystemSettingsConf
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="updateSystemSettingsConf",
                oauth2_scopes=[],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.CountedSystemSettings, http_res)
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(errors.ErrorData, http_res)
            raise errors.Error(response_data, http_res)
        if utils.match_response(http_res, ["401", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    async def update_async(
        self,
        *,
        api: Union[models.SystemSettingsConfAPI, models.SystemSettingsConfAPITypedDict],
        pii: Union[models.SystemSettingsConfPii, models.SystemSettingsConfPiiTypedDict],
        proxy: Union[
            models.SystemSettingsConfProxy, models.SystemSettingsConfProxyTypedDict
        ],
        system: Union[
            models.SystemSettingsConfSystem, models.SystemSettingsConfSystemTypedDict
        ],
        upgrade_group_settings: Union[
            models.UpgradeGroupSettings, models.UpgradeGroupSettingsTypedDict
        ],
        workers: Union[
            models.SystemSettingsConfWorkers, models.SystemSettingsConfWorkersTypedDict
        ],
        backups: Optional[
            Union[
                models.SystemSettingsConfBackups,
                models.SystemSettingsConfBackupsTypedDict,
            ]
        ] = None,
        custom_logo: Optional[
            Union[
                models.SystemSettingsConfCustomLogo,
                models.SystemSettingsConfCustomLogoTypedDict,
            ]
        ] = None,
        rollback: Optional[
            Union[
                models.SystemSettingsConfRollback,
                models.SystemSettingsConfRollbackTypedDict,
            ]
        ] = None,
        shutdown: Optional[
            Union[
                models.SystemSettingsConfShutdown,
                models.SystemSettingsConfShutdownTypedDict,
            ]
        ] = None,
        sni: Optional[
            Union[models.SystemSettingsConfSni, models.SystemSettingsConfSniTypedDict]
        ] = None,
        sockets: Optional[
            Union[
                models.SystemSettingsConfSockets,
                models.SystemSettingsConfSocketsTypedDict,
            ]
        ] = None,
        support: Optional[
            Union[
                models.SystemSettingsConfSupport,
                models.SystemSettingsConfSupportTypedDict,
            ]
        ] = None,
        tls: Optional[
            Union[models.SystemSettingsConfTLS, models.SystemSettingsConfTLSTypedDict]
        ] = None,
        upgrade_settings: Optional[
            Union[models.UpgradeSettings, models.UpgradeSettingsTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.CountedSystemSettings:
        r"""Update Cribl system settings

        Update Cribl system settings

        :param api:
        :param pii:
        :param proxy:
        :param system:
        :param upgrade_group_settings:
        :param workers:
        :param backups:
        :param custom_logo:
        :param rollback:
        :param shutdown:
        :param sni:
        :param sockets:
        :param support:
        :param tls:
        :param upgrade_settings:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.SystemSettingsConf(
            api=utils.get_pydantic_model(api, models.SystemSettingsConfAPI),
            backups=utils.get_pydantic_model(
                backups, Optional[models.SystemSettingsConfBackups]
            ),
            custom_logo=utils.get_pydantic_model(
                custom_logo, Optional[models.SystemSettingsConfCustomLogo]
            ),
            pii=utils.get_pydantic_model(pii, models.SystemSettingsConfPii),
            proxy=utils.get_pydantic_model(proxy, models.SystemSettingsConfProxy),
            rollback=utils.get_pydantic_model(
                rollback, Optional[models.SystemSettingsConfRollback]
            ),
            shutdown=utils.get_pydantic_model(
                shutdown, Optional[models.SystemSettingsConfShutdown]
            ),
            sni=utils.get_pydantic_model(sni, Optional[models.SystemSettingsConfSni]),
            sockets=utils.get_pydantic_model(
                sockets, Optional[models.SystemSettingsConfSockets]
            ),
            support=utils.get_pydantic_model(
                support, Optional[models.SystemSettingsConfSupport]
            ),
            system=utils.get_pydantic_model(system, models.SystemSettingsConfSystem),
            tls=utils.get_pydantic_model(tls, Optional[models.SystemSettingsConfTLS]),
            upgrade_group_settings=utils.get_pydantic_model(
                upgrade_group_settings, models.UpgradeGroupSettings
            ),
            upgrade_settings=utils.get_pydantic_model(
                upgrade_settings, Optional[models.UpgradeSettings]
            ),
            workers=utils.get_pydantic_model(workers, models.SystemSettingsConfWorkers),
        )

        req = self._build_request_async(
            method="PATCH",
            path="/system/settings/conf",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.SystemSettingsConf
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="updateSystemSettingsConf",
                oauth2_scopes=[],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.CountedSystemSettings, http_res)
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(errors.ErrorData, http_res)
            raise errors.Error(response_data, http_res)
        if utils.match_response(http_res, ["401", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)
