"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .metadata1type import Metadata1Type, Metadata1TypeTypedDict
from cribl_control_plane.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AddHecTokenRequestTypedDict(TypedDict):
    token: str
    description: NotRequired[str]
    enabled: NotRequired[bool]
    metadata: NotRequired[List[Metadata1TypeTypedDict]]


class AddHecTokenRequest(BaseModel):
    token: str

    description: Optional[str] = None

    enabled: Optional[bool] = None

    metadata: Optional[List[Metadata1Type]] = None
