"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 11e87ecebe77

from __future__ import annotations
from cribl_control_plane import utils
from enum import Enum


class AuthenticationMethodOptions(str, Enum, metaclass=utils.OpenEnumMeta):
    MANUAL = "manual"
    SECRET = "secret"
    CLIENT_SECRET = "clientSecret"
    CLIENT_CERT = "clientCert"
    CLIENT_ASSERTION = "clientAssertion"
    CLIENT_ASSERTION_RPC = "clientAssertion_rpc"
