"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane import utils
from enum import Enum


class AuthenticationMethodOptionsAutoSecret(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""AWS authentication method. Choose Auto to use IAM roles."""

    # Auto
    AUTO = "auto"
    # Secret Key pair
    SECRET = "secret"
