"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane import models, utils
from cribl_control_plane.types import BaseModel
from cribl_control_plane.utils import validate_open_enum
from enum import Enum
import pydantic
from pydantic import field_serializer
from pydantic.functional_validators import PlainValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AuthTypeAuthenticationMethod(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Enter credentials directly, or select a stored secret"""

    MANUAL = "manual"
    SECRET = "secret"
    MANUAL_API_KEY = "manualAPIKey"
    TEXT_SECRET = "textSecret"


class AuthTypeTypedDict(TypedDict):
    disabled: NotRequired[bool]
    username: NotRequired[str]
    password: NotRequired[str]
    auth_type: NotRequired[AuthTypeAuthenticationMethod]
    r"""Enter credentials directly, or select a stored secret"""
    credentials_secret: NotRequired[str]
    r"""Select or create a secret that references your credentials"""
    manual_api_key: NotRequired[str]
    r"""Enter API key directly"""
    text_secret: NotRequired[str]
    r"""Select or create a stored text secret"""


class AuthType(BaseModel):
    disabled: Optional[bool] = True

    username: Optional[str] = None

    password: Optional[str] = None

    auth_type: Annotated[
        Annotated[
            Optional[AuthTypeAuthenticationMethod],
            PlainValidator(validate_open_enum(False)),
        ],
        pydantic.Field(alias="authType"),
    ] = AuthTypeAuthenticationMethod.MANUAL
    r"""Enter credentials directly, or select a stored secret"""

    credentials_secret: Annotated[
        Optional[str], pydantic.Field(alias="credentialsSecret")
    ] = None
    r"""Select or create a secret that references your credentials"""

    manual_api_key: Annotated[Optional[str], pydantic.Field(alias="manualAPIKey")] = (
        None
    )
    r"""Enter API key directly"""

    text_secret: Annotated[Optional[str], pydantic.Field(alias="textSecret")] = None
    r"""Select or create a stored text secret"""

    @field_serializer("auth_type")
    def serialize_auth_type(self, value):
        if isinstance(value, str):
            try:
                return models.AuthTypeAuthenticationMethod(value)
            except ValueError:
                return value
        return value
