"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BranchInfoTypedDict(TypedDict):
    id: str
    r"""Unique identifier."""
    src_group: NotRequired[str]
    r"""Fleet or group id this entity was inherited from when served by a Config Helper for a child fleet. Present when inherited from parent, including when the child has a local overlay. Omitted when the entity is local and not inherited. Display-only; never persisted."""
    src_overridden: NotRequired[bool]
    r"""If true, the child fleet has a local overlay on an inherited entity. Omitted when inherited and unmodified, or when local and not inherited. Display-only; never persisted."""


class BranchInfo(BaseModel):
    id: str
    r"""Unique identifier."""

    src_group: Annotated[Optional[str], pydantic.Field(alias="__srcGroup")] = None
    r"""Fleet or group id this entity was inherited from when served by a Config Helper for a child fleet. Present when inherited from parent, including when the child has a local overlay. Omitted when the entity is local and not inherited. Display-only; never persisted."""

    src_overridden: Annotated[
        Optional[bool], pydantic.Field(alias="__srcOverridden")
    ] = None
    r"""If true, the child fleet has a local overlay on an inherited entity. Omitted when inherited and unmodified, or when local and not inherited. Display-only; never persisted."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["__srcGroup", "__srcOverridden"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    BranchInfo.model_rebuild()
except NameError:
    pass
