"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ColumnMappingConfOutputClickHouseTypedDict(TypedDict):
    column_name: str
    r"""Name of the column in ClickHouse that will store field value"""
    column_value_expression: str
    r"""JavaScript expression to compute value to be inserted into ClickHouse table"""
    column_type: NotRequired[str]
    r"""Type of the column in the ClickHouse database"""


class ColumnMappingConfOutputClickHouse(BaseModel):
    column_name: Annotated[str, pydantic.Field(alias="columnName")]
    r"""Name of the column in ClickHouse that will store field value"""

    column_value_expression: Annotated[
        str, pydantic.Field(alias="columnValueExpression")
    ]
    r"""JavaScript expression to compute value to be inserted into ClickHouse table"""

    column_type: Annotated[Optional[str], pydantic.Field(alias="columnType")] = None
    r"""Type of the column in the ClickHouse database"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["columnType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ColumnMappingConfOutputClickHouse.model_rebuild()
except NameError:
    pass
