"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .systemsettingsconf import SystemSettingsConf, SystemSettingsConfTypedDict
from cribl_control_plane.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class CountedSystemSettingsConfTypedDict(TypedDict):
    count: int
    r"""Number of items returned in the items array."""
    items: List[SystemSettingsConfTypedDict]
    r"""The list of items returned in this response."""


class CountedSystemSettingsConf(BaseModel):
    count: int
    r"""Number of items returned in the items array."""

    items: List[SystemSettingsConf]
    r"""The list of items returned in this response."""
