"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .packuninstallinfo import PackUninstallInfo, PackUninstallInfoTypedDict
from cribl_control_plane.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class CountedPackUninstallInfoTypedDict(TypedDict):
    count: int
    r"""number of items present in the items array"""
    items: List[PackUninstallInfoTypedDict]
    r"""List of items in this response."""


class CountedPackUninstallInfo(BaseModel):
    count: int
    r"""number of items present in the items array"""

    items: List[PackUninstallInfo]
    r"""List of items in this response."""
