"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .systemsettingsconfresponse import (
    SystemSettingsConfResponse,
    SystemSettingsConfResponseTypedDict,
)
from cribl_control_plane.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class CountedSystemSettingsConfResponseTypedDict(TypedDict):
    count: int
    r"""Number of items returned in the items array."""
    items: List[SystemSettingsConfResponseTypedDict]
    r"""The list of items returned in this response."""


class CountedSystemSettingsConfResponse(BaseModel):
    count: int
    r"""Number of items returned in the items array."""

    items: List[SystemSettingsConfResponse]
    r"""The list of items returned in this response."""
