"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .gitrevertresult import GitRevertResult, GitRevertResultTypedDict
from cribl_control_plane.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class CountedGitRevertResultTypedDict(TypedDict):
    count: int
    r"""number of items present in the items array"""
    items: List[GitRevertResultTypedDict]
    r"""List of items in this response."""


class CountedGitRevertResult(BaseModel):
    count: int
    r"""number of items present in the items array"""

    items: List[GitRevertResult]
    r"""List of items in this response."""
