"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .outputtestresponse import OutputTestResponse, OutputTestResponseTypedDict
from cribl_control_plane.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class CountedOutputTestResponseTypedDict(TypedDict):
    count: int
    r"""Number of items returned in the items array."""
    items: List[OutputTestResponseTypedDict]
    r"""The list of items returned in this response."""


class CountedOutputTestResponse(BaseModel):
    count: int
    r"""Number of items returned in the items array."""

    items: List[OutputTestResponse]
    r"""The list of items returned in this response."""
