"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .hiddendefaultbreakersoptionsdatabasecollectorconf import (
    HiddenDefaultBreakersOptionsDatabaseCollectorConf,
)
from cribl_control_plane import models
from cribl_control_plane.types import BaseModel
import pydantic
from pydantic import field_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DatabaseCollectorConfStateTrackingTypedDict(TypedDict):
    enabled: NotRequired[bool]
    r"""Enable tracking of collection progress between consecutive scheduled executions."""


class DatabaseCollectorConfStateTracking(BaseModel):
    enabled: Optional[bool] = None
    r"""Enable tracking of collection progress between consecutive scheduled executions."""


class DatabaseCollectorConfSchedulingTypedDict(TypedDict):
    state_tracking: NotRequired[DatabaseCollectorConfStateTrackingTypedDict]


class DatabaseCollectorConfScheduling(BaseModel):
    state_tracking: Annotated[
        Optional[DatabaseCollectorConfStateTracking],
        pydantic.Field(alias="stateTracking"),
    ] = None


class DatabaseCollectorConfTypedDict(TypedDict):
    connection_id: str
    r"""Select an existing Connection, or go to Knowledge > Database Connections to add one"""
    query: str
    r"""An expression that resolves to the query string for selecting data from the database. Has access to the special ${earliest} and ${latest} variables, which will resolve to the Collector run's start and end time."""
    query_validation_enabled: NotRequired[bool]
    r"""Enforces a basic query validation that allows only a single 'select' statement. Disable for more complex queries or when using semicolons. Caution: Disabling query validation allows DDL and DML statements to be executed, which could be destructive to your database."""
    default_breakers: NotRequired[HiddenDefaultBreakersOptionsDatabaseCollectorConf]
    scheduling: NotRequired[DatabaseCollectorConfSchedulingTypedDict]


class DatabaseCollectorConf(BaseModel):
    connection_id: Annotated[str, pydantic.Field(alias="connectionId")]
    r"""Select an existing Connection, or go to Knowledge > Database Connections to add one"""

    query: str
    r"""An expression that resolves to the query string for selecting data from the database. Has access to the special ${earliest} and ${latest} variables, which will resolve to the Collector run's start and end time."""

    query_validation_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="queryValidationEnabled")
    ] = True
    r"""Enforces a basic query validation that allows only a single 'select' statement. Disable for more complex queries or when using semicolons. Caution: Disabling query validation allows DDL and DML statements to be executed, which could be destructive to your database."""

    default_breakers: Annotated[
        Optional[HiddenDefaultBreakersOptionsDatabaseCollectorConf],
        pydantic.Field(alias="defaultBreakers"),
    ] = None

    scheduling: Annotated[
        Optional[DatabaseCollectorConfScheduling], pydantic.Field(alias="__scheduling")
    ] = None

    @field_serializer("default_breakers")
    def serialize_default_breakers(self, value):
        if isinstance(value, str):
            try:
                return models.HiddenDefaultBreakersOptionsDatabaseCollectorConf(value)
            except ValueError:
                return value
        return value
