"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 00d2590a9f21

from __future__ import annotations
from cribl_control_plane.types import BaseModel
from typing_extensions import TypedDict


class FunctionConfSchemaLocalSearchDatatypeParserTypedDict(TypedDict):
    pass


class FunctionConfSchemaLocalSearchDatatypeParser(BaseModel):
    pass
