"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
from cribl_control_plane.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetCriblLakeDatasetByLakeIDAndIDRequestTypedDict(TypedDict):
    lake_id: str
    r"""The <code>id</code> of the Lake that contains the Lake Dataset to get."""
    id: str
    r"""The <code>id</code> of the Lake Dataset to get."""
    include_metrics: NotRequired[bool]
    r"""Set to <code>true</code> to include storage metrics for each Lake Dataset. Otherwise, <code>false</code> (default). Requires a Cribl Lake metrics license."""


class GetCriblLakeDatasetByLakeIDAndIDRequest(BaseModel):
    lake_id: Annotated[
        str,
        pydantic.Field(alias="lakeId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The <code>id</code> of the Lake that contains the Lake Dataset to get."""

    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The <code>id</code> of the Lake Dataset to get."""

    include_metrics: Annotated[
        Optional[bool],
        pydantic.Field(alias="includeMetrics"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Set to <code>true</code> to include storage metrics for each Lake Dataset. Otherwise, <code>false</code> (default). Requires a Cribl Lake metrics license."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["includeMetrics"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
