"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .countedinputresponse import CountedInputResponse, CountedInputResponseTypedDict
from .paginatedinputresponse import (
    PaginatedInputResponse,
    PaginatedInputResponseTypedDict,
)
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
from cribl_control_plane.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
from pydantic import model_serializer
from typing import Awaitable, Callable, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class GetInputSystemByPackRequestTypedDict(TypedDict):
    pack: str
    r"""The <code>id</code> of the Pack."""
    type: NotRequired[List[str]]
    r"""Type of Source to include in the results. Each request can include only one <code>type</code> parameter; multiple parameters per request are not supported."""
    offset: NotRequired[int]
    r"""Pagination offset"""
    limit: NotRequired[int]
    r"""Maximum number of items to return"""


class GetInputSystemByPackRequest(BaseModel):
    pack: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The <code>id</code> of the Pack."""

    type: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Type of Source to include in the results. Each request can include only one <code>type</code> parameter; multiple parameters per request are not supported."""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Pagination offset"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Maximum number of items to return"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "offset", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


GetInputSystemByPackResponseBodyTypedDict = TypeAliasType(
    "GetInputSystemByPackResponseBodyTypedDict",
    Union[CountedInputResponseTypedDict, PaginatedInputResponseTypedDict],
)
r"""List of Source objects."""


GetInputSystemByPackResponseBody = TypeAliasType(
    "GetInputSystemByPackResponseBody",
    Union[CountedInputResponse, PaginatedInputResponse],
)
r"""List of Source objects."""


class GetInputSystemByPackResponseTypedDict(TypedDict):
    result: GetInputSystemByPackResponseBodyTypedDict


class GetInputSystemByPackResponse(BaseModel):
    next: Union[
        Callable[[], Optional[GetInputSystemByPackResponse]],
        Callable[[], Awaitable[Optional[GetInputSystemByPackResponse]]],
    ]

    result: GetInputSystemByPackResponseBody
