"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
from cribl_control_plane.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetOutputStatusSystemOutputsByPackAndIDRequestTypedDict(TypedDict):
    id: str
    r"""The <code>id</code> of the Destination to get the status for."""
    pack: str
    r"""The <code>id</code> of the Pack to get."""
    metrics: NotRequired[bool]
    r"""Set to true <code>true</code> to include metrics for each Destination. Otherwise, <code>false</code> (default)."""
    type: NotRequired[bool]
    r"""Set to <code>true</code> to prefix the Destination <code>id</code> with the Destination type. Otherwise, <code>false</code> (default)."""


class GetOutputStatusSystemOutputsByPackAndIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The <code>id</code> of the Destination to get the status for."""

    pack: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The <code>id</code> of the Pack to get."""

    metrics: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Set to true <code>true</code> to include metrics for each Destination. Otherwise, <code>false</code> (default)."""

    type: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Set to <code>true</code> to prefix the Destination <code>id</code> with the Destination type. Otherwise, <code>false</code> (default)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["metrics", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
