"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .gitfilerename import GitFileRename, GitFileRenameTypedDict
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AuthorTypedDict(TypedDict):
    r"""Author of the Git commit, including email and display name."""

    email: str
    r"""Email address of the commit author."""
    name: str
    r"""Display name of the commit author."""


class Author(BaseModel):
    r"""Author of the Git commit, including email and display name."""

    email: str
    r"""Email address of the commit author."""

    name: str
    r"""Display name of the commit author."""


class GitCommitSummaryFilesTypedDict(TypedDict):
    r"""Files affected by the commit, grouped by change type."""

    created: NotRequired[List[str]]
    r"""Array of file paths that were created in the commit."""
    deleted: NotRequired[List[str]]
    r"""Array of file paths that were deleted in the commit."""
    modified: NotRequired[List[str]]
    r"""Array of file paths that were modified in the commit."""
    renamed: NotRequired[List[GitFileRenameTypedDict]]
    r"""Array of file rename operations, each containing the original path and the new path."""


class GitCommitSummaryFiles(BaseModel):
    r"""Files affected by the commit, grouped by change type."""

    created: Optional[List[str]] = None
    r"""Array of file paths that were created in the commit."""

    deleted: Optional[List[str]] = None
    r"""Array of file paths that were deleted in the commit."""

    modified: Optional[List[str]] = None
    r"""Array of file paths that were modified in the commit."""

    renamed: Optional[List[GitFileRename]] = None
    r"""Array of file rename operations, each containing the original path and the new path."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["created", "deleted", "modified", "renamed"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SummaryTypedDict(TypedDict):
    r"""Summary of line changes in the commit."""

    changes: int
    r"""Total number of lines changed (insertions plus deletions)."""
    deletions: int
    r"""Number of lines deleted."""
    insertions: int
    r"""Number of lines inserted."""


class Summary(BaseModel):
    r"""Summary of line changes in the commit."""

    changes: int
    r"""Total number of lines changed (insertions plus deletions)."""

    deletions: int
    r"""Number of lines deleted."""

    insertions: int
    r"""Number of lines inserted."""


class GitCommitSummaryTypedDict(TypedDict):
    branch: str
    r"""Name of the Git branch the commit was made on."""
    commit: str
    r"""Full SHA-1 hash of the new commit."""
    summary: SummaryTypedDict
    r"""Summary of line changes in the commit."""
    author: NotRequired[AuthorTypedDict]
    r"""Author of the Git commit, including email and display name."""
    files: NotRequired[GitCommitSummaryFilesTypedDict]
    r"""Files affected by the commit, grouped by change type."""


class GitCommitSummary(BaseModel):
    branch: str
    r"""Name of the Git branch the commit was made on."""

    commit: str
    r"""Full SHA-1 hash of the new commit."""

    summary: Summary
    r"""Summary of line changes in the commit."""

    author: Optional[Author] = None
    r"""Author of the Git commit, including email and display name."""

    files: Optional[GitCommitSummaryFiles] = None
    r"""Files affected by the commit, grouped by change type."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["author", "files"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
