"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane import utils
from enum import Enum


class HealthOptionsStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Overall health status of the Source or Destination."""

    GREEN = "Green"
    RED = "Red"
    UNKNOWN = "Unknown"
    YELLOW = "Yellow"
