"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .healthoverlaystatus import HealthOverlayStatus, HealthOverlayStatusTypedDict
from cribl_control_plane import models, utils
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
from enum import Enum
import pydantic
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Role(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Leader Node role: <code>primary</code> or <code>standby</code>."""

    PRIMARY = "primary"
    STANDBY = "standby"


class HealthServerStatusStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Health state: <code>healthy</code>, <code>standby</code>, or <code>shutting down</code>."""

    HEALTHY = "healthy"
    SHUTTING_DOWN = "shutting down"
    STANDBY = "standby"


class HealthServerStatusTypedDict(TypedDict):
    r"""Health status of the Leader or Worker Node."""

    overlay: HealthOverlayStatusTypedDict
    start_time: int
    r"""Timestamp (in Unix time) when the Cribl process started."""
    status: HealthServerStatusStatus
    r"""Health state: <code>healthy</code>, <code>standby</code>, or <code>shutting down</code>."""
    role: NotRequired[Role]
    r"""Leader Node role: <code>primary</code> or <code>standby</code>."""


class HealthServerStatus(BaseModel):
    r"""Health status of the Leader or Worker Node."""

    overlay: HealthOverlayStatus

    start_time: Annotated[int, pydantic.Field(alias="startTime")]
    r"""Timestamp (in Unix time) when the Cribl process started."""

    status: HealthServerStatusStatus
    r"""Health state: <code>healthy</code>, <code>standby</code>, or <code>shutting down</code>."""

    role: Optional[Role] = None
    r"""Leader Node role: <code>primary</code> or <code>standby</code>."""

    @field_serializer("role")
    def serialize_role(self, value):
        if isinstance(value, str):
            try:
                return models.Role(value)
            except ValueError:
                return value
        return value

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.HealthServerStatusStatus(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["role"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    HealthServerStatus.model_rebuild()
except NameError:
    pass
