"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class HealthCountTypeTypedDict(TypedDict):
    green: int
    r"""Number of Worker Processes reporting a healthy (Green) status."""
    red: int
    r"""Number of Worker Processes reporting a critical (Red) status."""
    unknown: int
    r"""Number of Worker Processes reporting an unknown health status."""
    yellow: int
    r"""Number of Worker Processes reporting a degraded (Yellow) status."""


class HealthCountType(BaseModel):
    green: Annotated[int, pydantic.Field(alias="Green")]
    r"""Number of Worker Processes reporting a healthy (Green) status."""

    red: Annotated[int, pydantic.Field(alias="Red")]
    r"""Number of Worker Processes reporting a critical (Red) status."""

    unknown: Annotated[int, pydantic.Field(alias="Unknown")]
    r"""Number of Worker Processes reporting an unknown health status."""

    yellow: Annotated[int, pydantic.Field(alias="Yellow")]
    r"""Number of Worker Processes reporting a degraded (Yellow) status."""


try:
    HealthCountType.model_rebuild()
except NameError:
    pass
