"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane import models, utils
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
from enum import Enum
import pydantic
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Origin(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Feature that created the Source."""

    DATA_SOURCE_DISCOVERY = "data_source_discovery"


class InputCollectionOriginDataSourceDiscoveryWithDestinationArnConstraintTypedDict(
    TypedDict
):
    r"""Read-only metadata that records how the Source was created. Preserved on update when omitted from the request body. Cannot be set on create."""

    origin: NotRequired[Origin]
    r"""Feature that created the Source."""
    destination_arn: NotRequired[str]
    r"""ARN of the S3 bucket or Firehose delivery stream configured as the Source."""
    source_arn: NotRequired[str]
    r"""ARN of the AWS resource that produces the logs."""


class InputCollectionOriginDataSourceDiscoveryWithDestinationArnConstraint(BaseModel):
    r"""Read-only metadata that records how the Source was created. Preserved on update when omitted from the request body. Cannot be set on create."""

    origin: Optional[Origin] = None
    r"""Feature that created the Source."""

    destination_arn: Annotated[
        Optional[str], pydantic.Field(alias="destinationArn")
    ] = None
    r"""ARN of the S3 bucket or Firehose delivery stream configured as the Source."""

    source_arn: Annotated[Optional[str], pydantic.Field(alias="sourceArn")] = None
    r"""ARN of the AWS resource that produces the logs."""

    @field_serializer("origin")
    def serialize_origin(self, value):
        if isinstance(value, str):
            try:
                return models.Origin(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["origin", "destinationArn", "sourceArn"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    InputCollectionOriginDataSourceDiscoveryWithDestinationArnConstraint.model_rebuild()
except NameError:
    pass
