"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .certoptionstype import CertOptionsType, CertOptionsTypeTypedDict
from .connectionconfinputcollection import (
    ConnectionConfInputCollection,
    ConnectionConfInputCollectionTypedDict,
)
from .logleveloptionsdebugerror import LogLevelOptionsDebugError
from .metadataconfinputcollection import (
    MetadataConfInputCollection,
    MetadataConfInputCollectionTypedDict,
)
from .pqtype import PqType, PqTypeTypedDict
from .retryrulestypecodesenableheader import (
    RetryRulesTypeCodesEnableHeader,
    RetryRulesTypeCodesEnableHeaderTypedDict,
)
from cribl_control_plane import models, utils
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
from enum import Enum
import pydantic
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class InputMicrosoftGraphType(str, Enum):
    MICROSOFT_GRAPH = "microsoft_graph"


class InputMicrosoftGraphAuthenticationMethod(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Select authentication method."""

    OAUTH = "oauth"
    OAUTH_SECRET = "oauthSecret"
    OAUTH_CERT = "oauthCert"


class InputMicrosoftGraphSubscriptionPlan(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Microsoft 365 subscription plan for your organization, typically Microsoft 365 Enterprise"""

    # Microsoft 365 Enterprise
    ENTERPRISE_GCC = "enterprise_gcc"
    # Microsoft 365 GCC
    GCC = "gcc"
    # Microsoft 365 GCC High
    GCC_HIGH = "gcc_high"
    # Microsoft 365 DoD
    DOD = "dod"
    # Microsoft 365 China (21Vianet)
    CHINA = "china"


class InputMicrosoftGraphInputTypedDict(TypedDict):
    type: InputMicrosoftGraphType
    url: str
    r"""Microsoft Graph API endpoint URL. (ex. https://graph.microsoft.com/v1.0/admin/exchange/tracing/messageTraces)"""
    interval: int
    r"""How often (in minutes) to run the report. Must divide evenly into 60 minutes to create a predictable schedule, or Save will fail."""
    id: NotRequired[str]
    r"""Unique ID for this input"""
    disabled: NotRequired[bool]
    r"""If true, the Source is disabled and will not collect data."""
    pipeline: NotRequired[str]
    r"""Pipeline to process data from this Source before sending it through the Routes"""
    send_to_routes: NotRequired[bool]
    r"""Select whether to send data to Routes, or directly to Destinations."""
    environment: NotRequired[str]
    r"""Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere."""
    pq_enabled: NotRequired[bool]
    r"""Use a disk queue to minimize data loss when connected services block. See [Cribl Docs](https://docs.cribl.io/stream/persistent-queues) for PQ defaults (Cribl-managed Cloud Workers) and configuration options (on-prem and hybrid Workers)."""
    streamtags: NotRequired[List[str]]
    r"""Tags for filtering and grouping in @{product}"""
    connections: NotRequired[List[ConnectionConfInputCollectionTypedDict]]
    r"""Direct connections to Destinations, and optionally via a Pipeline or a Pack"""
    pq: NotRequired[PqTypeTypedDict]
    start_date: NotRequired[str]
    r"""Backward offset for the search range's head. (E.g.: -3h@h) Microsoft Graph data is delayed; this parameter (with Date range end) compensates for delay and gaps."""
    end_date: NotRequired[str]
    r"""Backward offset for the search range's tail. (E.g.: -2h@h) Microsoft Graph data is delayed; this parameter (with Date range start) compensates for delay and gaps."""
    timeout: NotRequired[float]
    r"""HTTP request inactivity timeout. Maximum is 2400 (40 minutes); enter 0 to wait indefinitely."""
    disable_time_filter: NotRequired[bool]
    r"""Disables time filtering of events when a date range is specified."""
    max_pages: NotRequired[int]
    r"""Maximum number of pages to retrieve per collection task. Set to 0 to retrieve all pages."""
    auth_type: NotRequired[InputMicrosoftGraphAuthenticationMethod]
    r"""Select authentication method."""
    keep_alive_time: NotRequired[float]
    r"""How often workers should check in with the scheduler to keep job subscription alive"""
    job_timeout: NotRequired[str]
    r"""Maximum time the job is allowed to run. Time unit defaults to seconds if not specified (examples: 30, 45s, 15m). Enter 0 for unlimited time."""
    max_missed_keep_alives: NotRequired[float]
    r"""The number of Keep Alive Time periods before an inactive worker will have its job subscription revoked."""
    ttl: NotRequired[str]
    r"""Time to keep the job's artifacts on disk after job completion. This also affects how long a job is listed in the Job Inspector."""
    ignore_group_jobs_limit: NotRequired[bool]
    r"""When enabled, this job's artifacts are not counted toward the Worker Group's finished job artifacts limit. Artifacts will be removed only after the Collector's configured time to live."""
    metadata: NotRequired[List[MetadataConfInputCollectionTypedDict]]
    r"""Fields to add to events from this input"""
    reschedule_dropped_tasks: NotRequired[bool]
    r"""Reschedule tasks that failed with non-fatal errors"""
    max_task_reschedule: NotRequired[float]
    r"""Maximum number of times a task can be rescheduled"""
    log_level: NotRequired[LogLevelOptionsDebugError]
    r"""Log Level (verbosity) for collection runtime behavior."""
    retry_rules: NotRequired[RetryRulesTypeCodesEnableHeaderTypedDict]
    description: NotRequired[str]
    r"""Optional description for this configuration."""
    client_secret: NotRequired[str]
    r"""client_secret to pass in the OAuth request parameter."""
    tenant_id: NotRequired[str]
    r"""Directory ID (tenant identifier) in Azure Active Directory."""
    client_id: NotRequired[str]
    r"""client_id to pass in the OAuth request parameter."""
    resource: NotRequired[str]
    r"""Resource to pass in the OAuth request parameter."""
    plan_type: NotRequired[InputMicrosoftGraphSubscriptionPlan]
    r"""Microsoft 365 subscription plan for your organization, typically Microsoft 365 Enterprise"""
    text_secret: NotRequired[str]
    r"""Select or create a secret that references your client_secret to pass in the OAuth request parameter."""
    cert_options: NotRequired[CertOptionsTypeTypedDict]
    template_environment: NotRequired[str]
    r"""Binds 'environment' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'environment' at runtime."""
    template_streamtags: NotRequired[str]
    r"""Binds 'streamtags' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'streamtags' at runtime."""
    template_url: NotRequired[str]
    r"""Binds 'url' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'url' at runtime."""
    template_tenant_id: NotRequired[str]
    r"""Binds 'tenantId' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'tenantId' at runtime."""
    template_client_id: NotRequired[str]
    r"""Binds 'clientId' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'clientId' at runtime."""
    template_resource: NotRequired[str]
    r"""Binds 'resource' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'resource' at runtime."""
    template_plan_type: NotRequired[str]
    r"""Binds 'planType' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'planType' at runtime."""


class InputMicrosoftGraphInput(BaseModel):
    type: InputMicrosoftGraphType

    url: str
    r"""Microsoft Graph API endpoint URL. (ex. https://graph.microsoft.com/v1.0/admin/exchange/tracing/messageTraces)"""

    interval: int
    r"""How often (in minutes) to run the report. Must divide evenly into 60 minutes to create a predictable schedule, or Save will fail."""

    id: Optional[str] = None
    r"""Unique ID for this input"""

    disabled: Optional[bool] = None
    r"""If true, the Source is disabled and will not collect data."""

    pipeline: Optional[str] = None
    r"""Pipeline to process data from this Source before sending it through the Routes"""

    send_to_routes: Annotated[Optional[bool], pydantic.Field(alias="sendToRoutes")] = (
        None
    )
    r"""Select whether to send data to Routes, or directly to Destinations."""

    environment: Optional[str] = None
    r"""Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere."""

    pq_enabled: Annotated[Optional[bool], pydantic.Field(alias="pqEnabled")] = None
    r"""Use a disk queue to minimize data loss when connected services block. See [Cribl Docs](https://docs.cribl.io/stream/persistent-queues) for PQ defaults (Cribl-managed Cloud Workers) and configuration options (on-prem and hybrid Workers)."""

    streamtags: Optional[List[str]] = None
    r"""Tags for filtering and grouping in @{product}"""

    connections: Optional[List[ConnectionConfInputCollection]] = None
    r"""Direct connections to Destinations, and optionally via a Pipeline or a Pack"""

    pq: Optional[PqType] = None

    start_date: Annotated[Optional[str], pydantic.Field(alias="startDate")] = None
    r"""Backward offset for the search range's head. (E.g.: -3h@h) Microsoft Graph data is delayed; this parameter (with Date range end) compensates for delay and gaps."""

    end_date: Annotated[Optional[str], pydantic.Field(alias="endDate")] = None
    r"""Backward offset for the search range's tail. (E.g.: -2h@h) Microsoft Graph data is delayed; this parameter (with Date range start) compensates for delay and gaps."""

    timeout: Optional[float] = None
    r"""HTTP request inactivity timeout. Maximum is 2400 (40 minutes); enter 0 to wait indefinitely."""

    disable_time_filter: Annotated[
        Optional[bool], pydantic.Field(alias="disableTimeFilter")
    ] = None
    r"""Disables time filtering of events when a date range is specified."""

    max_pages: Annotated[Optional[int], pydantic.Field(alias="maxPages")] = None
    r"""Maximum number of pages to retrieve per collection task. Set to 0 to retrieve all pages."""

    auth_type: Annotated[
        Optional[InputMicrosoftGraphAuthenticationMethod],
        pydantic.Field(alias="authType"),
    ] = None
    r"""Select authentication method."""

    keep_alive_time: Annotated[
        Optional[float], pydantic.Field(alias="keepAliveTime")
    ] = None
    r"""How often workers should check in with the scheduler to keep job subscription alive"""

    job_timeout: Annotated[Optional[str], pydantic.Field(alias="jobTimeout")] = None
    r"""Maximum time the job is allowed to run. Time unit defaults to seconds if not specified (examples: 30, 45s, 15m). Enter 0 for unlimited time."""

    max_missed_keep_alives: Annotated[
        Optional[float], pydantic.Field(alias="maxMissedKeepAlives")
    ] = None
    r"""The number of Keep Alive Time periods before an inactive worker will have its job subscription revoked."""

    ttl: Optional[str] = None
    r"""Time to keep the job's artifacts on disk after job completion. This also affects how long a job is listed in the Job Inspector."""

    ignore_group_jobs_limit: Annotated[
        Optional[bool], pydantic.Field(alias="ignoreGroupJobsLimit")
    ] = None
    r"""When enabled, this job's artifacts are not counted toward the Worker Group's finished job artifacts limit. Artifacts will be removed only after the Collector's configured time to live."""

    metadata: Optional[List[MetadataConfInputCollection]] = None
    r"""Fields to add to events from this input"""

    reschedule_dropped_tasks: Annotated[
        Optional[bool], pydantic.Field(alias="rescheduleDroppedTasks")
    ] = None
    r"""Reschedule tasks that failed with non-fatal errors"""

    max_task_reschedule: Annotated[
        Optional[float], pydantic.Field(alias="maxTaskReschedule")
    ] = None
    r"""Maximum number of times a task can be rescheduled"""

    log_level: Annotated[
        Optional[LogLevelOptionsDebugError], pydantic.Field(alias="logLevel")
    ] = None
    r"""Log Level (verbosity) for collection runtime behavior."""

    retry_rules: Annotated[
        Optional[RetryRulesTypeCodesEnableHeader], pydantic.Field(alias="retryRules")
    ] = None

    description: Optional[str] = None
    r"""Optional description for this configuration."""

    client_secret: Annotated[Optional[str], pydantic.Field(alias="clientSecret")] = None
    r"""client_secret to pass in the OAuth request parameter."""

    tenant_id: Annotated[Optional[str], pydantic.Field(alias="tenantId")] = None
    r"""Directory ID (tenant identifier) in Azure Active Directory."""

    client_id: Annotated[Optional[str], pydantic.Field(alias="clientId")] = None
    r"""client_id to pass in the OAuth request parameter."""

    resource: Optional[str] = None
    r"""Resource to pass in the OAuth request parameter."""

    plan_type: Annotated[
        Optional[InputMicrosoftGraphSubscriptionPlan], pydantic.Field(alias="planType")
    ] = None
    r"""Microsoft 365 subscription plan for your organization, typically Microsoft 365 Enterprise"""

    text_secret: Annotated[Optional[str], pydantic.Field(alias="textSecret")] = None
    r"""Select or create a secret that references your client_secret to pass in the OAuth request parameter."""

    cert_options: Annotated[
        Optional[CertOptionsType], pydantic.Field(alias="certOptions")
    ] = None

    template_environment: Annotated[
        Optional[str], pydantic.Field(alias="__template_environment")
    ] = None
    r"""Binds 'environment' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'environment' at runtime."""

    template_streamtags: Annotated[
        Optional[str], pydantic.Field(alias="__template_streamtags")
    ] = None
    r"""Binds 'streamtags' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'streamtags' at runtime."""

    template_url: Annotated[Optional[str], pydantic.Field(alias="__template_url")] = (
        None
    )
    r"""Binds 'url' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'url' at runtime."""

    template_tenant_id: Annotated[
        Optional[str], pydantic.Field(alias="__template_tenantId")
    ] = None
    r"""Binds 'tenantId' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'tenantId' at runtime."""

    template_client_id: Annotated[
        Optional[str], pydantic.Field(alias="__template_clientId")
    ] = None
    r"""Binds 'clientId' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'clientId' at runtime."""

    template_resource: Annotated[
        Optional[str], pydantic.Field(alias="__template_resource")
    ] = None
    r"""Binds 'resource' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'resource' at runtime."""

    template_plan_type: Annotated[
        Optional[str], pydantic.Field(alias="__template_planType")
    ] = None
    r"""Binds 'planType' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'planType' at runtime."""

    @field_serializer("auth_type")
    def serialize_auth_type(self, value):
        if isinstance(value, str):
            try:
                return models.InputMicrosoftGraphAuthenticationMethod(value)
            except ValueError:
                return value
        return value

    @field_serializer("log_level")
    def serialize_log_level(self, value):
        if isinstance(value, str):
            try:
                return models.LogLevelOptionsDebugError(value)
            except ValueError:
                return value
        return value

    @field_serializer("plan_type")
    def serialize_plan_type(self, value):
        if isinstance(value, str):
            try:
                return models.InputMicrosoftGraphSubscriptionPlan(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "disabled",
                "pipeline",
                "sendToRoutes",
                "environment",
                "pqEnabled",
                "streamtags",
                "connections",
                "pq",
                "startDate",
                "endDate",
                "timeout",
                "disableTimeFilter",
                "maxPages",
                "authType",
                "keepAliveTime",
                "jobTimeout",
                "maxMissedKeepAlives",
                "ttl",
                "ignoreGroupJobsLimit",
                "metadata",
                "rescheduleDroppedTasks",
                "maxTaskReschedule",
                "logLevel",
                "retryRules",
                "description",
                "clientSecret",
                "tenantId",
                "clientId",
                "resource",
                "planType",
                "textSecret",
                "certOptions",
                "__template_environment",
                "__template_streamtags",
                "__template_url",
                "__template_tenantId",
                "__template_clientId",
                "__template_resource",
                "__template_planType",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    InputMicrosoftGraphInput.model_rebuild()
except NameError:
    pass
