"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .inputappscope import InputAppscope, InputAppscopeTypedDict
from .inputazureblob import InputAzureBlob, InputAzureBlobTypedDict
from .inputcloudflarehec import InputCloudflareHec, InputCloudflareHecTypedDict
from .inputcollection import InputCollection, InputCollectionTypedDict
from .inputconfluentcloud import InputConfluentCloud, InputConfluentCloudTypedDict
from .inputcribl import InputCribl, InputCriblTypedDict
from .inputcriblhttp import InputCriblHTTP, InputCriblHTTPTypedDict
from .inputcribllakehttp import InputCriblLakeHTTP, InputCriblLakeHTTPTypedDict
from .inputcriblmetrics import InputCriblmetrics, InputCriblmetricsTypedDict
from .inputcribltcp import InputCriblTCP, InputCriblTCPTypedDict
from .inputcrowdstrike import InputCrowdstrike, InputCrowdstrikeTypedDict
from .inputdatadogagent import InputDatadogAgent, InputDatadogAgentTypedDict
from .inputdatagen import InputDatagen, InputDatagenTypedDict
from .inputedgeprometheus import InputEdgePrometheus, InputEdgePrometheusTypedDict
from .inputelastic import InputElastic, InputElasticTypedDict
from .inputeventhub import InputEventhub, InputEventhubTypedDict
from .inputexec import InputExec, InputExecTypedDict
from .inputfile import InputFile, InputFileTypedDict
from .inputfirehose import InputFirehose, InputFirehoseTypedDict
from .inputgooglepubsub import InputGooglePubsub, InputGooglePubsubTypedDict
from .inputgrafana_union import InputGrafanaUnion, InputGrafanaUnionTypedDict
from .inputhttp import InputHTTP, InputHTTPTypedDict
from .inputhttpraw import InputHTTPRaw, InputHTTPRawTypedDict
from .inputjournalfiles import InputJournalFiles, InputJournalFilesTypedDict
from .inputkafka import InputKafka, InputKafkaTypedDict
from .inputkinesis import InputKinesis, InputKinesisTypedDict
from .inputkubeevents import InputKubeEvents, InputKubeEventsTypedDict
from .inputkubelogs import InputKubeLogs, InputKubeLogsTypedDict
from .inputkubemetrics import InputKubeMetrics, InputKubeMetricsTypedDict
from .inputloki import InputLoki, InputLokiTypedDict
from .inputmetrics import InputMetrics, InputMetricsTypedDict
from .inputmodeldriventelemetry import (
    InputModelDrivenTelemetry,
    InputModelDrivenTelemetryTypedDict,
)
from .inputmsk import InputMsk, InputMskTypedDict
from .inputnetflow import InputNetflow, InputNetflowTypedDict
from .inputoffice365mgmt import InputOffice365Mgmt, InputOffice365MgmtTypedDict
from .inputoffice365msgtrace import (
    InputOffice365MsgTrace,
    InputOffice365MsgTraceTypedDict,
)
from .inputoffice365service import InputOffice365Service, InputOffice365ServiceTypedDict
from .inputopentelemetry import InputOpenTelemetry, InputOpenTelemetryTypedDict
from .inputprometheus import InputPrometheus, InputPrometheusTypedDict
from .inputprometheusrw import InputPrometheusRw, InputPrometheusRwTypedDict
from .inputrawudp import InputRawUDP, InputRawUDPTypedDict
from .inputs3 import InputS3, InputS3TypedDict
from .inputs3inventory import InputS3Inventory, InputS3InventoryTypedDict
from .inputsecuritylake import InputSecurityLake, InputSecurityLakeTypedDict
from .inputsnmp import InputSnmp, InputSnmpTypedDict
from .inputsplunk import InputSplunk, InputSplunkTypedDict
from .inputsplunkhec import InputSplunkHec, InputSplunkHecTypedDict
from .inputsplunksearch import InputSplunkSearch, InputSplunkSearchTypedDict
from .inputsqs import InputSqs, InputSqsTypedDict
from .inputsyslog_union import InputSyslogUnion, InputSyslogUnionTypedDict
from .inputsystemmetrics import InputSystemMetrics, InputSystemMetricsTypedDict
from .inputsystemstate import InputSystemState, InputSystemStateTypedDict
from .inputtcp import InputTCP, InputTCPTypedDict
from .inputtcpjson import InputTcpjson, InputTcpjsonTypedDict
from .inputwef import InputWef, InputWefTypedDict
from .inputwindowsmetrics import InputWindowsMetrics, InputWindowsMetricsTypedDict
from .inputwineventlogs import InputWinEventLogs, InputWinEventLogsTypedDict
from .inputwiz import InputWiz, InputWizTypedDict
from .inputwizwebhook import InputWizWebhook, InputWizWebhookTypedDict
from .inputzscalerhec import InputZscalerHec, InputZscalerHecTypedDict
from cribl_control_plane.types import BaseModel
from cribl_control_plane.utils.unions import parse_open_union
from functools import partial
from pydantic import ConfigDict
from pydantic.functional_validators import BeforeValidator
from typing import Any, Literal, Union
from typing_extensions import Annotated, TypeAliasType


InputTypedDict = TypeAliasType(
    "InputTypedDict",
    Union[
        InputDatagenTypedDict,
        InputCriblTypedDict,
        InputKubeEventsTypedDict,
        InputCriblmetricsTypedDict,
        InputKubeMetricsTypedDict,
        InputCollectionTypedDict,
        InputSystemStateTypedDict,
        InputWindowsMetricsTypedDict,
        InputSystemMetricsTypedDict,
        InputJournalFilesTypedDict,
        InputExecTypedDict,
        InputKubeLogsTypedDict,
        InputModelDrivenTelemetryTypedDict,
        InputRawUDPTypedDict,
        InputWinEventLogsTypedDict,
        InputSnmpTypedDict,
        InputMetricsTypedDict,
        InputCriblTCPTypedDict,
        InputNetflowTypedDict,
        InputTcpjsonTypedDict,
        InputGooglePubsubTypedDict,
        InputFirehoseTypedDict,
        InputWizTypedDict,
        InputOffice365ServiceTypedDict,
        InputCriblHTTPTypedDict,
        InputTCPTypedDict,
        InputDatadogAgentTypedDict,
        InputFileTypedDict,
        InputSplunkTypedDict,
        InputOffice365MgmtTypedDict,
        InputAppscopeTypedDict,
        InputWefTypedDict,
        InputWizWebhookTypedDict,
        InputHTTPRawTypedDict,
        InputKafkaTypedDict,
        InputZscalerHecTypedDict,
        InputHTTPTypedDict,
        InputLokiTypedDict,
        InputCriblLakeHTTPTypedDict,
        InputCloudflareHecTypedDict,
        InputEventhubTypedDict,
        InputConfluentCloudTypedDict,
        InputPrometheusRwTypedDict,
        InputOpenTelemetryTypedDict,
        InputAzureBlobTypedDict,
        InputElasticTypedDict,
        InputSplunkHecTypedDict,
        InputSplunkSearchTypedDict,
        InputSqsTypedDict,
        InputKinesisTypedDict,
        InputOffice365MsgTraceTypedDict,
        InputEdgePrometheusTypedDict,
        InputCrowdstrikeTypedDict,
        InputMskTypedDict,
        InputS3TypedDict,
        InputPrometheusTypedDict,
        InputSecurityLakeTypedDict,
        InputS3InventoryTypedDict,
        InputSyslogUnionTypedDict,
        InputGrafanaUnionTypedDict,
    ],
)


class UnknownInput(BaseModel):
    r"""A Input variant the SDK doesn't recognize. Preserves the raw payload."""

    type: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_INPUT_VARIANTS: dict[str, Any] = {
    "collection": InputCollection,
    "kafka": InputKafka,
    "msk": InputMsk,
    "http": InputHTTP,
    "splunk": InputSplunk,
    "splunk_search": InputSplunkSearch,
    "splunk_hec": InputSplunkHec,
    "azure_blob": InputAzureBlob,
    "elastic": InputElastic,
    "confluent_cloud": InputConfluentCloud,
    "grafana": InputGrafanaUnion,
    "loki": InputLoki,
    "prometheus_rw": InputPrometheusRw,
    "prometheus": InputPrometheus,
    "edge_prometheus": InputEdgePrometheus,
    "office365_mgmt": InputOffice365Mgmt,
    "office365_service": InputOffice365Service,
    "office365_msg_trace": InputOffice365MsgTrace,
    "eventhub": InputEventhub,
    "exec": InputExec,
    "firehose": InputFirehose,
    "google_pubsub": InputGooglePubsub,
    "cribl": InputCribl,
    "cribl_tcp": InputCriblTCP,
    "cribl_http": InputCriblHTTP,
    "cribl_lake_http": InputCriblLakeHTTP,
    "tcpjson": InputTcpjson,
    "system_metrics": InputSystemMetrics,
    "system_state": InputSystemState,
    "kube_metrics": InputKubeMetrics,
    "kube_logs": InputKubeLogs,
    "kube_events": InputKubeEvents,
    "windows_metrics": InputWindowsMetrics,
    "crowdstrike": InputCrowdstrike,
    "datadog_agent": InputDatadogAgent,
    "datagen": InputDatagen,
    "http_raw": InputHTTPRaw,
    "kinesis": InputKinesis,
    "criblmetrics": InputCriblmetrics,
    "metrics": InputMetrics,
    "s3": InputS3,
    "s3_inventory": InputS3Inventory,
    "snmp": InputSnmp,
    "open_telemetry": InputOpenTelemetry,
    "model_driven_telemetry": InputModelDrivenTelemetry,
    "sqs": InputSqs,
    "syslog": InputSyslogUnion,
    "file": InputFile,
    "tcp": InputTCP,
    "appscope": InputAppscope,
    "wef": InputWef,
    "win_event_logs": InputWinEventLogs,
    "raw_udp": InputRawUDP,
    "journal_files": InputJournalFiles,
    "wiz": InputWiz,
    "wiz_webhook": InputWizWebhook,
    "netflow": InputNetflow,
    "security_lake": InputSecurityLake,
    "zscaler_hec": InputZscalerHec,
    "cloudflare_hec": InputCloudflareHec,
}


Input = Annotated[
    Union[
        InputCollection,
        InputKafka,
        InputMsk,
        InputHTTP,
        InputSplunk,
        InputSplunkSearch,
        InputSplunkHec,
        InputAzureBlob,
        InputElastic,
        InputConfluentCloud,
        InputGrafanaUnion,
        InputLoki,
        InputPrometheusRw,
        InputPrometheus,
        InputEdgePrometheus,
        InputOffice365Mgmt,
        InputOffice365Service,
        InputOffice365MsgTrace,
        InputEventhub,
        InputExec,
        InputFirehose,
        InputGooglePubsub,
        InputCribl,
        InputCriblTCP,
        InputCriblHTTP,
        InputCriblLakeHTTP,
        InputTcpjson,
        InputSystemMetrics,
        InputSystemState,
        InputKubeMetrics,
        InputKubeLogs,
        InputKubeEvents,
        InputWindowsMetrics,
        InputCrowdstrike,
        InputDatadogAgent,
        InputDatagen,
        InputHTTPRaw,
        InputKinesis,
        InputCriblmetrics,
        InputMetrics,
        InputS3,
        InputS3Inventory,
        InputSnmp,
        InputOpenTelemetry,
        InputModelDrivenTelemetry,
        InputSqs,
        InputSyslogUnion,
        InputFile,
        InputTCP,
        InputAppscope,
        InputWef,
        InputWinEventLogs,
        InputRawUDP,
        InputJournalFiles,
        InputWiz,
        InputWizWebhook,
        InputNetflow,
        InputSecurityLake,
        InputZscalerHec,
        InputCloudflareHec,
        UnknownInput,
    ],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="type",
            variants=_INPUT_VARIANTS,
            unknown_cls=UnknownInput,
            union_name="Input",
        )
    ),
]
