"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .connectionconfinputcollection import (
    ConnectionConfInputCollection,
    ConnectionConfInputCollectionTypedDict,
)
from .metadataconfinputcollection import (
    MetadataConfInputCollection,
    MetadataConfInputCollectionTypedDict,
)
from .pqtype import PqType, PqTypeTypedDict
from .ruleconfinputkubemetrics import (
    RuleConfInputKubeMetrics,
    RuleConfInputKubeMetricsTypedDict,
)
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
from enum import Enum
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class InputKubeEventsType(str, Enum):
    KUBE_EVENTS = "kube_events"


class InputKubeEventsInputTypedDict(TypedDict):
    type: InputKubeEventsType
    id: NotRequired[str]
    r"""Unique ID for this input"""
    disabled: NotRequired[bool]
    r"""If true, the Source is disabled and will not collect data."""
    pipeline: NotRequired[str]
    r"""Pipeline to process data from this Source before sending it through the Routes"""
    send_to_routes: NotRequired[bool]
    r"""Select whether to send data to Routes, or directly to Destinations."""
    environment: NotRequired[str]
    r"""Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere."""
    pq_enabled: NotRequired[bool]
    r"""Use a disk queue to minimize data loss when connected services block. See [Cribl Docs](https://docs.cribl.io/stream/persistent-queues) for PQ defaults (Cribl-managed Cloud Workers) and configuration options (on-prem and hybrid Workers)."""
    streamtags: NotRequired[List[str]]
    r"""Tags for filtering and grouping in @{product}"""
    connections: NotRequired[List[ConnectionConfInputCollectionTypedDict]]
    r"""Direct connections to Destinations, and optionally via a Pipeline or a Pack"""
    pq: NotRequired[PqTypeTypedDict]
    rules: NotRequired[List[RuleConfInputKubeMetricsTypedDict]]
    r"""Filtering on event fields"""
    metadata: NotRequired[List[MetadataConfInputCollectionTypedDict]]
    r"""Fields to add to events from this input"""
    description: NotRequired[str]
    r"""Optional description for this configuration."""
    template_environment: NotRequired[str]
    r"""Binds 'environment' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'environment' at runtime."""
    template_streamtags: NotRequired[str]
    r"""Binds 'streamtags' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'streamtags' at runtime."""


class InputKubeEventsInput(BaseModel):
    type: InputKubeEventsType

    id: Optional[str] = None
    r"""Unique ID for this input"""

    disabled: Optional[bool] = None
    r"""If true, the Source is disabled and will not collect data."""

    pipeline: Optional[str] = None
    r"""Pipeline to process data from this Source before sending it through the Routes"""

    send_to_routes: Annotated[Optional[bool], pydantic.Field(alias="sendToRoutes")] = (
        None
    )
    r"""Select whether to send data to Routes, or directly to Destinations."""

    environment: Optional[str] = None
    r"""Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere."""

    pq_enabled: Annotated[Optional[bool], pydantic.Field(alias="pqEnabled")] = None
    r"""Use a disk queue to minimize data loss when connected services block. See [Cribl Docs](https://docs.cribl.io/stream/persistent-queues) for PQ defaults (Cribl-managed Cloud Workers) and configuration options (on-prem and hybrid Workers)."""

    streamtags: Optional[List[str]] = None
    r"""Tags for filtering and grouping in @{product}"""

    connections: Optional[List[ConnectionConfInputCollection]] = None
    r"""Direct connections to Destinations, and optionally via a Pipeline or a Pack"""

    pq: Optional[PqType] = None

    rules: Optional[List[RuleConfInputKubeMetrics]] = None
    r"""Filtering on event fields"""

    metadata: Optional[List[MetadataConfInputCollection]] = None
    r"""Fields to add to events from this input"""

    description: Optional[str] = None
    r"""Optional description for this configuration."""

    template_environment: Annotated[
        Optional[str], pydantic.Field(alias="__template_environment")
    ] = None
    r"""Binds 'environment' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'environment' at runtime."""

    template_streamtags: Annotated[
        Optional[str], pydantic.Field(alias="__template_streamtags")
    ] = None
    r"""Binds 'streamtags' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'streamtags' at runtime."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "disabled",
                "pipeline",
                "sendToRoutes",
                "environment",
                "pqEnabled",
                "streamtags",
                "connections",
                "pq",
                "rules",
                "metadata",
                "description",
                "__template_environment",
                "__template_streamtags",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    InputKubeEventsInput.model_rebuild()
except NameError:
    pass
