"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ItemsTypeConnectionsOptionalTypedDict(TypedDict):
    pipeline: NotRequired[str]
    output: NotRequired[str]


class ItemsTypeConnectionsOptional(BaseModel):
    pipeline: Optional[str] = None

    output: Optional[str] = None
