"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel
from typing_extensions import TypedDict


class KeyValueMetadataConfOutputFilesystemTypedDict(TypedDict):
    key: str
    value: str


class KeyValueMetadataConfOutputFilesystem(BaseModel):
    key: str

    value: str
