"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: cf5a974e7e9f

from __future__ import annotations
from cribl_control_plane import utils
from enum import Enum


class LakehouseConnectionType(str, Enum, metaclass=utils.OpenEnumMeta):
    CACHE = "cache"
    ZERO_POINT = "zeroPoint"
