"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel
from typing_extensions import TypedDict


class MetadataConfAddHecTokenRequestTypedDict(TypedDict):
    name: str
    r"""Key name for the metadata entry."""
    value: str
    r"""Value for the metadata entry. Can be a static string or a JavaScript expression."""


class MetadataConfAddHecTokenRequest(BaseModel):
    name: str
    r"""Key name for the metadata entry."""

    value: str
    r"""Value for the metadata entry. Can be a static string or a JavaScript expression."""
