"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apischeme import APIScheme
from .awstypeheartbeatmetadata import (
    AwsTypeHeartbeatMetadata,
    AwsTypeHeartbeatMetadataTypedDict,
)
from .azuretypeheartbeatmetadata import (
    AzureTypeHeartbeatMetadata,
    AzureTypeHeartbeatMetadataTypedDict,
)
from .hbcriblinfo import HBCriblInfo, HBCriblInfoTypedDict
from .heartbeatmetadata import HeartbeatMetadata, HeartbeatMetadataTypedDict
from .hostostypeheartbeatmetadata import (
    HostOsTypeHeartbeatMetadata,
    HostOsTypeHeartbeatMetadataTypedDict,
)
from .kubetypeheartbeatmetadata import (
    KubeTypeHeartbeatMetadata,
    KubeTypeHeartbeatMetadataTypedDict,
)
from .outpostnodeinfo import OutpostNodeInfo, OutpostNodeInfoTypedDict
from cribl_control_plane import models
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import field_serializer, model_serializer
from typing import Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class OsTypedDict(TypedDict):
    addresses: List[str]


class Os(BaseModel):
    addresses: List[str]


OsUnionTypedDict = TypeAliasType(
    "OsUnionTypedDict", Union[OsTypedDict, HostOsTypeHeartbeatMetadataTypedDict]
)


OsUnion = TypeAliasType("OsUnion", Union[Os, HostOsTypeHeartbeatMetadata])


class NodeProvidedInfoTypedDict(TypedDict):
    architecture: str
    cpus: float
    cribl: HBCriblInfoTypedDict
    env: Dict[str, str]
    hostname: str
    node: str
    platform: str
    release: str
    totalmem: float
    api_port: NotRequired[float]
    api_scheme: NotRequired[APIScheme]
    aws: NotRequired[AwsTypeHeartbeatMetadataTypedDict]
    azure: NotRequired[AzureTypeHeartbeatMetadataTypedDict]
    conn_ip: NotRequired[str]
    free_disk_space: NotRequired[float]
    host_os: NotRequired[HostOsTypeHeartbeatMetadataTypedDict]
    is_captain: NotRequired[bool]
    is_saas_worker: NotRequired[bool]
    kube: NotRequired[KubeTypeHeartbeatMetadataTypedDict]
    local_time: NotRequired[float]
    metadata: NotRequired[HeartbeatMetadataTypedDict]
    os: NotRequired[OsUnionTypedDict]
    outpost: NotRequired[OutpostNodeInfoTypedDict]
    total_disk_space: NotRequired[float]


class NodeProvidedInfo(BaseModel):
    architecture: str

    cpus: float

    cribl: HBCriblInfo

    env: Dict[str, str]

    hostname: str

    node: str

    platform: str

    release: str

    totalmem: float

    api_port: Annotated[Optional[float], pydantic.Field(alias="apiPort")] = None

    api_scheme: Annotated[Optional[APIScheme], pydantic.Field(alias="apiScheme")] = None

    aws: Optional[AwsTypeHeartbeatMetadata] = None

    azure: Optional[AzureTypeHeartbeatMetadata] = None

    conn_ip: Optional[str] = None

    free_disk_space: Annotated[
        Optional[float], pydantic.Field(alias="freeDiskSpace")
    ] = None

    host_os: Annotated[
        Optional[HostOsTypeHeartbeatMetadata], pydantic.Field(alias="hostOs")
    ] = None

    is_captain: Annotated[Optional[bool], pydantic.Field(alias="isCaptain")] = None

    is_saas_worker: Annotated[Optional[bool], pydantic.Field(alias="isSaasWorker")] = (
        None
    )

    kube: Optional[KubeTypeHeartbeatMetadata] = None

    local_time: Annotated[Optional[float], pydantic.Field(alias="localTime")] = None

    metadata: Optional[HeartbeatMetadata] = None

    os: Optional[OsUnion] = None

    outpost: Optional[OutpostNodeInfo] = None

    total_disk_space: Annotated[
        Optional[float], pydantic.Field(alias="totalDiskSpace")
    ] = None

    @field_serializer("api_scheme")
    def serialize_api_scheme(self, value):
        if isinstance(value, str):
            try:
                return models.APIScheme(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "apiPort",
                "apiScheme",
                "aws",
                "azure",
                "conn_ip",
                "freeDiskSpace",
                "hostOs",
                "isCaptain",
                "isSaasWorker",
                "kube",
                "localTime",
                "metadata",
                "os",
                "outpost",
                "totalDiskSpace",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    NodeProvidedInfo.model_rebuild()
except NameError:
    pass
