"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane import utils
from enum import Enum


class NodeUpgradeState(int, Enum, metaclass=utils.OpenEnumMeta):
    ACTIVE = 0
    CURRENT = 1
    FAILED = 2
    SKIPPED = 3
