"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .awstype import AwsType, AwsTypeTypedDict
from .hbcriblinfo import HBCriblInfo, HBCriblInfoTypedDict
from .heartbeatmetadata import HeartbeatMetadata, HeartbeatMetadataTypedDict
from .hostostype import HostOsType, HostOsTypeTypedDict
from .kubetype import KubeType, KubeTypeTypedDict
from .outpostnodeinfo import OutpostNodeInfo, OutpostNodeInfoTypedDict
from cribl_control_plane.types import BaseModel
import pydantic
from typing import Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class Os2TypedDict(TypedDict):
    addresses: List[str]


class Os2(BaseModel):
    addresses: List[str]


class Os1TypedDict(TypedDict):
    addresses: List[str]
    enabled: bool
    id: str
    version: str


class Os1(BaseModel):
    addresses: List[str]

    enabled: bool

    id: str

    version: str


OsUnionTypedDict = TypeAliasType("OsUnionTypedDict", Union[Os2TypedDict, Os1TypedDict])


OsUnion = TypeAliasType("OsUnion", Union[Os2, Os1])


class NodeProvidedInfoTypedDict(TypedDict):
    architecture: str
    cpus: float
    cribl: HBCriblInfoTypedDict
    env: Dict[str, str]
    free_disk_space: float
    hostname: str
    node: str
    platform: str
    release: str
    total_disk_space: float
    totalmem: float
    aws: NotRequired[AwsTypeTypedDict]
    conn_ip: NotRequired[str]
    host_os: NotRequired[HostOsTypeTypedDict]
    is_saas_worker: NotRequired[bool]
    kube: NotRequired[KubeTypeTypedDict]
    local_time: NotRequired[float]
    metadata: NotRequired[HeartbeatMetadataTypedDict]
    os: NotRequired[OsUnionTypedDict]
    outpost: NotRequired[OutpostNodeInfoTypedDict]


class NodeProvidedInfo(BaseModel):
    architecture: str

    cpus: float

    cribl: HBCriblInfo

    env: Dict[str, str]

    free_disk_space: Annotated[float, pydantic.Field(alias="freeDiskSpace")]

    hostname: str

    node: str

    platform: str

    release: str

    total_disk_space: Annotated[float, pydantic.Field(alias="totalDiskSpace")]

    totalmem: float

    aws: Optional[AwsType] = None

    conn_ip: Optional[str] = None

    host_os: Annotated[Optional[HostOsType], pydantic.Field(alias="hostOs")] = None

    is_saas_worker: Annotated[Optional[bool], pydantic.Field(alias="isSaasWorker")] = (
        None
    )

    kube: Optional[KubeType] = None

    local_time: Annotated[Optional[float], pydantic.Field(alias="localTime")] = None

    metadata: Optional[HeartbeatMetadata] = None

    os: Optional[OsUnion] = None

    outpost: Optional[OutpostNodeInfo] = None
