"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apischeme import APIScheme
from .awstypeheartbeatmetadata import (
    AwsTypeHeartbeatMetadata,
    AwsTypeHeartbeatMetadataTypedDict,
)
from .azuretypeheartbeatmetadata import (
    AzureTypeHeartbeatMetadata,
    AzureTypeHeartbeatMetadataTypedDict,
)
from .hbcriblinfo import HBCriblInfo, HBCriblInfoTypedDict
from .heartbeatmetadata import HeartbeatMetadata, HeartbeatMetadataTypedDict
from .hostostypeheartbeatmetadata import (
    HostOsTypeHeartbeatMetadata,
    HostOsTypeHeartbeatMetadataTypedDict,
)
from .kubetypeheartbeatmetadata import (
    KubeTypeHeartbeatMetadata,
    KubeTypeHeartbeatMetadataTypedDict,
)
from .nodeosinfo import NodeOsInfo, NodeOsInfoTypedDict
from .ostypeheartbeatmetadata import (
    OsTypeHeartbeatMetadata,
    OsTypeHeartbeatMetadataTypedDict,
)
from .outpostnodeinfo import OutpostNodeInfo, OutpostNodeInfoTypedDict
from cribl_control_plane import models
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import field_serializer, model_serializer
from typing import Dict, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


OsTypedDict = TypeAliasType(
    "OsTypedDict", Union[NodeOsInfoTypedDict, OsTypeHeartbeatMetadataTypedDict]
)
r"""Operating system metadata collected from the node."""


Os = TypeAliasType("Os", Union[NodeOsInfo, OsTypeHeartbeatMetadata])
r"""Operating system metadata collected from the node."""


class NodeProvidedInfoTypedDict(TypedDict):
    architecture: str
    r"""CPU architecture."""
    cpus: int
    r"""Number of CPU cores available on the node."""
    cribl: HBCriblInfoTypedDict
    env: Dict[str, str]
    r"""Environment variables reported by the node."""
    hostname: str
    r"""Hostname reported by the node."""
    node: str
    r"""Node.js runtime version running on the node."""
    platform: str
    r"""Operating system platform."""
    release: str
    r"""Operating system kernel release."""
    totalmem: int
    r"""Total memory on the node, in bytes."""
    api_port: NotRequired[int]
    r"""API port exposed by the node."""
    api_scheme: NotRequired[APIScheme]
    aws: NotRequired[AwsTypeHeartbeatMetadataTypedDict]
    azure: NotRequired[AzureTypeHeartbeatMetadataTypedDict]
    conn_ip: NotRequired[str]
    r"""Remote <code>ip:port</code> for the worker socket."""
    free_disk_space: NotRequired[int]
    r"""Free disk space on the node, in bytes."""
    host_os: NotRequired[HostOsTypeHeartbeatMetadataTypedDict]
    is_captain: NotRequired[bool]
    r"""If <code>true</code>, the node considers itself the elected captain for its group. Otherwise, <code>false</code>."""
    is_saas_worker: NotRequired[bool]
    r"""If <code>true</code>, the node runs in Cribl.Cloud. Otherwise, <code>false</code>."""
    kube: NotRequired[KubeTypeHeartbeatMetadataTypedDict]
    local_time: NotRequired[int]
    r"""Local timestamp (in Unix time) on the node, in milliseconds."""
    metadata: NotRequired[HeartbeatMetadataTypedDict]
    os: NotRequired[OsTypedDict]
    r"""Operating system metadata collected from the node."""
    outpost: NotRequired[OutpostNodeInfoTypedDict]
    total_disk_space: NotRequired[int]
    r"""Total disk space on the node, in bytes."""


class NodeProvidedInfo(BaseModel):
    architecture: str
    r"""CPU architecture."""

    cpus: int
    r"""Number of CPU cores available on the node."""

    cribl: HBCriblInfo

    env: Dict[str, str]
    r"""Environment variables reported by the node."""

    hostname: str
    r"""Hostname reported by the node."""

    node: str
    r"""Node.js runtime version running on the node."""

    platform: str
    r"""Operating system platform."""

    release: str
    r"""Operating system kernel release."""

    totalmem: int
    r"""Total memory on the node, in bytes."""

    api_port: Annotated[Optional[int], pydantic.Field(alias="apiPort")] = None
    r"""API port exposed by the node."""

    api_scheme: Annotated[Optional[APIScheme], pydantic.Field(alias="apiScheme")] = None

    aws: Optional[AwsTypeHeartbeatMetadata] = None

    azure: Optional[AzureTypeHeartbeatMetadata] = None

    conn_ip: Optional[str] = None
    r"""Remote <code>ip:port</code> for the worker socket."""

    free_disk_space: Annotated[Optional[int], pydantic.Field(alias="freeDiskSpace")] = (
        None
    )
    r"""Free disk space on the node, in bytes."""

    host_os: Annotated[
        Optional[HostOsTypeHeartbeatMetadata], pydantic.Field(alias="hostOs")
    ] = None

    is_captain: Annotated[Optional[bool], pydantic.Field(alias="isCaptain")] = None
    r"""If <code>true</code>, the node considers itself the elected captain for its group. Otherwise, <code>false</code>."""

    is_saas_worker: Annotated[Optional[bool], pydantic.Field(alias="isSaasWorker")] = (
        None
    )
    r"""If <code>true</code>, the node runs in Cribl.Cloud. Otherwise, <code>false</code>."""

    kube: Optional[KubeTypeHeartbeatMetadata] = None

    local_time: Annotated[Optional[int], pydantic.Field(alias="localTime")] = None
    r"""Local timestamp (in Unix time) on the node, in milliseconds."""

    metadata: Optional[HeartbeatMetadata] = None

    os: Optional[Os] = None
    r"""Operating system metadata collected from the node."""

    outpost: Optional[OutpostNodeInfo] = None

    total_disk_space: Annotated[
        Optional[int], pydantic.Field(alias="totalDiskSpace")
    ] = None
    r"""Total disk space on the node, in bytes."""

    @field_serializer("api_scheme")
    def serialize_api_scheme(self, value):
        if isinstance(value, str):
            try:
                return models.APIScheme(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "apiPort",
                "apiScheme",
                "aws",
                "azure",
                "conn_ip",
                "freeDiskSpace",
                "hostOs",
                "isCaptain",
                "isSaasWorker",
                "kube",
                "localTime",
                "metadata",
                "os",
                "outpost",
                "totalDiskSpace",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    NodeProvidedInfo.model_rebuild()
except NameError:
    pass
