"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel
from typing import Any, Dict, List
from typing_extensions import TypedDict


class OutputSamplesResponseTypedDict(TypedDict):
    r"""Sample events from a Destination."""

    events: List[Dict[str, Any]]
    r"""Array of sample events returned from a Destination test."""


class OutputSamplesResponse(BaseModel):
    r"""Sample events from a Destination."""

    events: List[Dict[str, Any]]
    r"""Array of sample events returned from a Destination test."""
