"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .awsauthenticationmethodoptions import AwsAuthenticationMethodOptions
from .metadatatype import MetadataType, MetadataTypeTypedDict
from .onbackpressureoptions import OnBackpressureOptions
from .pqcompressoptions import PqCompressOptions
from .pqmodeoptions import PqModeOptions
from .pqonbackpressureoptions import PqOnBackpressureOptions
from .typegooglepubsuboption import TypeGooglePubsubOption
from cribl_control_plane import models
from cribl_control_plane.types import BaseModel
from cribl_control_plane.utils import validate_open_enum
import pydantic
from pydantic import field_serializer
from pydantic.functional_validators import PlainValidator
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class OutputGooglePubsubGooglePubsub5TypedDict(TypedDict):
    type: TypeGooglePubsubOption
    topic_name: str
    r"""ID of the topic to send events to."""
    pq_controls: MetadataTypeTypedDict
    on_backpressure: NotRequired[OnBackpressureOptions]
    r"""How to handle events when all receivers are exerting backpressure"""
    id: NotRequired[str]
    r"""Unique ID for this output"""
    pipeline: NotRequired[str]
    r"""Pipeline to process data before sending out to this output"""
    system_fields: NotRequired[List[str]]
    r"""Fields to automatically add to events, such as cribl_pipe. Supports wildcards."""
    environment: NotRequired[str]
    r"""Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere."""
    streamtags: NotRequired[List[str]]
    r"""Tags for filtering and grouping in @{product}"""
    create_topic: NotRequired[bool]
    r"""If enabled, create topic if it does not exist."""
    ordered_delivery: NotRequired[bool]
    r"""If enabled, send events in the order they were added to the queue. For this to work correctly, the process receiving events must have ordering enabled."""
    region: NotRequired[str]
    r"""Region to publish messages to. Select 'default' to allow Google to auto-select the nearest region. When using ordered delivery, the selected region must be allowed by message storage policy."""
    google_auth_method: NotRequired[AwsAuthenticationMethodOptions]
    r"""AWS authentication method. Choose Auto to use IAM roles."""
    service_account_credentials: NotRequired[str]
    r"""Contents of service account credentials (JSON keys) file downloaded from Google Cloud. To upload a file, click the upload button at this field's upper right."""
    secret: NotRequired[str]
    r"""Select or create a stored text secret"""
    batch_size: NotRequired[float]
    r"""The maximum number of items the Google API should batch before it sends them to the topic."""
    batch_timeout: NotRequired[float]
    r"""The maximum amount of time, in milliseconds, that the Google API should wait to send a batch (if the Batch size is not reached)."""
    max_queue_size: NotRequired[float]
    r"""Maximum number of queued batches before blocking."""
    max_record_size_kb: NotRequired[float]
    r"""Maximum size (KB) of batches to send."""
    flush_period: NotRequired[float]
    r"""Maximum time to wait before sending a batch (when batch size limit is not reached)"""
    max_in_progress: NotRequired[float]
    r"""The maximum number of in-progress API requests before backpressure is applied."""
    description: NotRequired[str]
    pq_strict_ordering: NotRequired[bool]
    r"""Use FIFO (first in, first out) processing. Disable to forward new events to receivers before queue is flushed."""
    pq_rate_per_sec: NotRequired[float]
    r"""Throttling rate (in events per second) to impose while writing to Destinations from PQ. Defaults to 0, which disables throttling."""
    pq_mode: NotRequired[PqModeOptions]
    r"""In Error mode, PQ writes events to the filesystem if the Destination is unavailable. In Backpressure mode, PQ writes events to the filesystem when it detects backpressure from the Destination. In Always On mode, PQ always writes events to the filesystem."""
    pq_max_buffer_size: NotRequired[float]
    r"""The maximum number of events to hold in memory before writing the events to disk"""
    pq_max_backpressure_sec: NotRequired[float]
    r"""How long (in seconds) to wait for backpressure to resolve before engaging the queue"""
    pq_max_file_size: NotRequired[str]
    r"""The maximum size to store in each queue file before closing and optionally compressing (KB, MB, etc.)"""
    pq_max_size: NotRequired[str]
    r"""The maximum disk space that the queue can consume (as an average per Worker Process) before queueing stops. Enter a numeral with units of KB, MB, etc."""
    pq_path: NotRequired[str]
    r"""The location for the persistent queue files. To this field's value, the system will append: /<worker-id>/<output-id>."""
    pq_compress: NotRequired[PqCompressOptions]
    r"""Codec to use to compress the persisted data"""
    pq_on_backpressure: NotRequired[PqOnBackpressureOptions]
    r"""How to handle events when the queue is exerting backpressure (full capacity or low disk). 'Block' is the same behavior as non-PQ blocking. 'Drop new data' throws away incoming data, while leaving the contents of the PQ unchanged."""


class OutputGooglePubsubGooglePubsub5(BaseModel):
    type: TypeGooglePubsubOption

    topic_name: Annotated[str, pydantic.Field(alias="topicName")]
    r"""ID of the topic to send events to."""

    pq_controls: Annotated[MetadataType, pydantic.Field(alias="pqControls")]

    on_backpressure: Annotated[
        Annotated[
            Optional[OnBackpressureOptions], PlainValidator(validate_open_enum(False))
        ],
        pydantic.Field(alias="onBackpressure"),
    ] = OnBackpressureOptions.BLOCK
    r"""How to handle events when all receivers are exerting backpressure"""

    id: Optional[str] = None
    r"""Unique ID for this output"""

    pipeline: Optional[str] = None
    r"""Pipeline to process data before sending out to this output"""

    system_fields: Annotated[
        Optional[List[str]], pydantic.Field(alias="systemFields")
    ] = None
    r"""Fields to automatically add to events, such as cribl_pipe. Supports wildcards."""

    environment: Optional[str] = None
    r"""Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere."""

    streamtags: Optional[List[str]] = None
    r"""Tags for filtering and grouping in @{product}"""

    create_topic: Annotated[Optional[bool], pydantic.Field(alias="createTopic")] = False
    r"""If enabled, create topic if it does not exist."""

    ordered_delivery: Annotated[
        Optional[bool], pydantic.Field(alias="orderedDelivery")
    ] = False
    r"""If enabled, send events in the order they were added to the queue. For this to work correctly, the process receiving events must have ordering enabled."""

    region: Optional[str] = None
    r"""Region to publish messages to. Select 'default' to allow Google to auto-select the nearest region. When using ordered delivery, the selected region must be allowed by message storage policy."""

    google_auth_method: Annotated[
        Annotated[
            Optional[AwsAuthenticationMethodOptions],
            PlainValidator(validate_open_enum(False)),
        ],
        pydantic.Field(alias="googleAuthMethod"),
    ] = AwsAuthenticationMethodOptions.AUTO
    r"""AWS authentication method. Choose Auto to use IAM roles."""

    service_account_credentials: Annotated[
        Optional[str], pydantic.Field(alias="serviceAccountCredentials")
    ] = None
    r"""Contents of service account credentials (JSON keys) file downloaded from Google Cloud. To upload a file, click the upload button at this field's upper right."""

    secret: Optional[str] = None
    r"""Select or create a stored text secret"""

    batch_size: Annotated[Optional[float], pydantic.Field(alias="batchSize")] = 1000
    r"""The maximum number of items the Google API should batch before it sends them to the topic."""

    batch_timeout: Annotated[Optional[float], pydantic.Field(alias="batchTimeout")] = (
        100
    )
    r"""The maximum amount of time, in milliseconds, that the Google API should wait to send a batch (if the Batch size is not reached)."""

    max_queue_size: Annotated[Optional[float], pydantic.Field(alias="maxQueueSize")] = (
        100
    )
    r"""Maximum number of queued batches before blocking."""

    max_record_size_kb: Annotated[
        Optional[float], pydantic.Field(alias="maxRecordSizeKB")
    ] = 256
    r"""Maximum size (KB) of batches to send."""

    flush_period: Annotated[Optional[float], pydantic.Field(alias="flushPeriod")] = 1
    r"""Maximum time to wait before sending a batch (when batch size limit is not reached)"""

    max_in_progress: Annotated[
        Optional[float], pydantic.Field(alias="maxInProgress")
    ] = 10
    r"""The maximum number of in-progress API requests before backpressure is applied."""

    description: Optional[str] = None

    pq_strict_ordering: Annotated[
        Optional[bool], pydantic.Field(alias="pqStrictOrdering")
    ] = True
    r"""Use FIFO (first in, first out) processing. Disable to forward new events to receivers before queue is flushed."""

    pq_rate_per_sec: Annotated[
        Optional[float], pydantic.Field(alias="pqRatePerSec")
    ] = 0
    r"""Throttling rate (in events per second) to impose while writing to Destinations from PQ. Defaults to 0, which disables throttling."""

    pq_mode: Annotated[
        Annotated[Optional[PqModeOptions], PlainValidator(validate_open_enum(False))],
        pydantic.Field(alias="pqMode"),
    ] = PqModeOptions.ERROR
    r"""In Error mode, PQ writes events to the filesystem if the Destination is unavailable. In Backpressure mode, PQ writes events to the filesystem when it detects backpressure from the Destination. In Always On mode, PQ always writes events to the filesystem."""

    pq_max_buffer_size: Annotated[
        Optional[float], pydantic.Field(alias="pqMaxBufferSize")
    ] = 42
    r"""The maximum number of events to hold in memory before writing the events to disk"""

    pq_max_backpressure_sec: Annotated[
        Optional[float], pydantic.Field(alias="pqMaxBackpressureSec")
    ] = 30
    r"""How long (in seconds) to wait for backpressure to resolve before engaging the queue"""

    pq_max_file_size: Annotated[
        Optional[str], pydantic.Field(alias="pqMaxFileSize")
    ] = "1 MB"
    r"""The maximum size to store in each queue file before closing and optionally compressing (KB, MB, etc.)"""

    pq_max_size: Annotated[Optional[str], pydantic.Field(alias="pqMaxSize")] = "5GB"
    r"""The maximum disk space that the queue can consume (as an average per Worker Process) before queueing stops. Enter a numeral with units of KB, MB, etc."""

    pq_path: Annotated[Optional[str], pydantic.Field(alias="pqPath")] = (
        "$CRIBL_HOME/state/queues"
    )
    r"""The location for the persistent queue files. To this field's value, the system will append: /<worker-id>/<output-id>."""

    pq_compress: Annotated[
        Annotated[
            Optional[PqCompressOptions], PlainValidator(validate_open_enum(False))
        ],
        pydantic.Field(alias="pqCompress"),
    ] = PqCompressOptions.NONE
    r"""Codec to use to compress the persisted data"""

    pq_on_backpressure: Annotated[
        Annotated[
            Optional[PqOnBackpressureOptions], PlainValidator(validate_open_enum(False))
        ],
        pydantic.Field(alias="pqOnBackpressure"),
    ] = PqOnBackpressureOptions.BLOCK
    r"""How to handle events when the queue is exerting backpressure (full capacity or low disk). 'Block' is the same behavior as non-PQ blocking. 'Drop new data' throws away incoming data, while leaving the contents of the PQ unchanged."""

    @field_serializer("on_backpressure")
    def serialize_on_backpressure(self, value):
        if isinstance(value, str):
            try:
                return models.OnBackpressureOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("google_auth_method")
    def serialize_google_auth_method(self, value):
        if isinstance(value, str):
            try:
                return models.AwsAuthenticationMethodOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("pq_mode")
    def serialize_pq_mode(self, value):
        if isinstance(value, str):
            try:
                return models.PqModeOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("pq_compress")
    def serialize_pq_compress(self, value):
        if isinstance(value, str):
            try:
                return models.PqCompressOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("pq_on_backpressure")
    def serialize_pq_on_backpressure(self, value):
        if isinstance(value, str):
            try:
                return models.PqOnBackpressureOptions(value)
            except ValueError:
                return value
        return value


class OutputGooglePubsubGooglePubsub4TypedDict(TypedDict):
    type: TypeGooglePubsubOption
    topic_name: str
    r"""ID of the topic to send events to."""
    on_backpressure: NotRequired[OnBackpressureOptions]
    r"""How to handle events when all receivers are exerting backpressure"""
    id: NotRequired[str]
    r"""Unique ID for this output"""
    pipeline: NotRequired[str]
    r"""Pipeline to process data before sending out to this output"""
    system_fields: NotRequired[List[str]]
    r"""Fields to automatically add to events, such as cribl_pipe. Supports wildcards."""
    environment: NotRequired[str]
    r"""Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere."""
    streamtags: NotRequired[List[str]]
    r"""Tags for filtering and grouping in @{product}"""
    create_topic: NotRequired[bool]
    r"""If enabled, create topic if it does not exist."""
    ordered_delivery: NotRequired[bool]
    r"""If enabled, send events in the order they were added to the queue. For this to work correctly, the process receiving events must have ordering enabled."""
    region: NotRequired[str]
    r"""Region to publish messages to. Select 'default' to allow Google to auto-select the nearest region. When using ordered delivery, the selected region must be allowed by message storage policy."""
    google_auth_method: NotRequired[AwsAuthenticationMethodOptions]
    r"""AWS authentication method. Choose Auto to use IAM roles."""
    service_account_credentials: NotRequired[str]
    r"""Contents of service account credentials (JSON keys) file downloaded from Google Cloud. To upload a file, click the upload button at this field's upper right."""
    secret: NotRequired[str]
    r"""Select or create a stored text secret"""
    batch_size: NotRequired[float]
    r"""The maximum number of items the Google API should batch before it sends them to the topic."""
    batch_timeout: NotRequired[float]
    r"""The maximum amount of time, in milliseconds, that the Google API should wait to send a batch (if the Batch size is not reached)."""
    max_queue_size: NotRequired[float]
    r"""Maximum number of queued batches before blocking."""
    max_record_size_kb: NotRequired[float]
    r"""Maximum size (KB) of batches to send."""
    flush_period: NotRequired[float]
    r"""Maximum time to wait before sending a batch (when batch size limit is not reached)"""
    max_in_progress: NotRequired[float]
    r"""The maximum number of in-progress API requests before backpressure is applied."""
    description: NotRequired[str]
    pq_strict_ordering: NotRequired[bool]
    r"""Use FIFO (first in, first out) processing. Disable to forward new events to receivers before queue is flushed."""
    pq_rate_per_sec: NotRequired[float]
    r"""Throttling rate (in events per second) to impose while writing to Destinations from PQ. Defaults to 0, which disables throttling."""
    pq_mode: NotRequired[PqModeOptions]
    r"""In Error mode, PQ writes events to the filesystem if the Destination is unavailable. In Backpressure mode, PQ writes events to the filesystem when it detects backpressure from the Destination. In Always On mode, PQ always writes events to the filesystem."""
    pq_max_buffer_size: NotRequired[float]
    r"""The maximum number of events to hold in memory before writing the events to disk"""
    pq_max_backpressure_sec: NotRequired[float]
    r"""How long (in seconds) to wait for backpressure to resolve before engaging the queue"""
    pq_max_file_size: NotRequired[str]
    r"""The maximum size to store in each queue file before closing and optionally compressing (KB, MB, etc.)"""
    pq_max_size: NotRequired[str]
    r"""The maximum disk space that the queue can consume (as an average per Worker Process) before queueing stops. Enter a numeral with units of KB, MB, etc."""
    pq_path: NotRequired[str]
    r"""The location for the persistent queue files. To this field's value, the system will append: /<worker-id>/<output-id>."""
    pq_compress: NotRequired[PqCompressOptions]
    r"""Codec to use to compress the persisted data"""
    pq_on_backpressure: NotRequired[PqOnBackpressureOptions]
    r"""How to handle events when the queue is exerting backpressure (full capacity or low disk). 'Block' is the same behavior as non-PQ blocking. 'Drop new data' throws away incoming data, while leaving the contents of the PQ unchanged."""
    pq_controls: NotRequired[MetadataTypeTypedDict]


class OutputGooglePubsubGooglePubsub4(BaseModel):
    type: TypeGooglePubsubOption

    topic_name: Annotated[str, pydantic.Field(alias="topicName")]
    r"""ID of the topic to send events to."""

    on_backpressure: Annotated[
        Annotated[
            Optional[OnBackpressureOptions], PlainValidator(validate_open_enum(False))
        ],
        pydantic.Field(alias="onBackpressure"),
    ] = OnBackpressureOptions.BLOCK
    r"""How to handle events when all receivers are exerting backpressure"""

    id: Optional[str] = None
    r"""Unique ID for this output"""

    pipeline: Optional[str] = None
    r"""Pipeline to process data before sending out to this output"""

    system_fields: Annotated[
        Optional[List[str]], pydantic.Field(alias="systemFields")
    ] = None
    r"""Fields to automatically add to events, such as cribl_pipe. Supports wildcards."""

    environment: Optional[str] = None
    r"""Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere."""

    streamtags: Optional[List[str]] = None
    r"""Tags for filtering and grouping in @{product}"""

    create_topic: Annotated[Optional[bool], pydantic.Field(alias="createTopic")] = False
    r"""If enabled, create topic if it does not exist."""

    ordered_delivery: Annotated[
        Optional[bool], pydantic.Field(alias="orderedDelivery")
    ] = False
    r"""If enabled, send events in the order they were added to the queue. For this to work correctly, the process receiving events must have ordering enabled."""

    region: Optional[str] = None
    r"""Region to publish messages to. Select 'default' to allow Google to auto-select the nearest region. When using ordered delivery, the selected region must be allowed by message storage policy."""

    google_auth_method: Annotated[
        Annotated[
            Optional[AwsAuthenticationMethodOptions],
            PlainValidator(validate_open_enum(False)),
        ],
        pydantic.Field(alias="googleAuthMethod"),
    ] = AwsAuthenticationMethodOptions.AUTO
    r"""AWS authentication method. Choose Auto to use IAM roles."""

    service_account_credentials: Annotated[
        Optional[str], pydantic.Field(alias="serviceAccountCredentials")
    ] = None
    r"""Contents of service account credentials (JSON keys) file downloaded from Google Cloud. To upload a file, click the upload button at this field's upper right."""

    secret: Optional[str] = None
    r"""Select or create a stored text secret"""

    batch_size: Annotated[Optional[float], pydantic.Field(alias="batchSize")] = 1000
    r"""The maximum number of items the Google API should batch before it sends them to the topic."""

    batch_timeout: Annotated[Optional[float], pydantic.Field(alias="batchTimeout")] = (
        100
    )
    r"""The maximum amount of time, in milliseconds, that the Google API should wait to send a batch (if the Batch size is not reached)."""

    max_queue_size: Annotated[Optional[float], pydantic.Field(alias="maxQueueSize")] = (
        100
    )
    r"""Maximum number of queued batches before blocking."""

    max_record_size_kb: Annotated[
        Optional[float], pydantic.Field(alias="maxRecordSizeKB")
    ] = 256
    r"""Maximum size (KB) of batches to send."""

    flush_period: Annotated[Optional[float], pydantic.Field(alias="flushPeriod")] = 1
    r"""Maximum time to wait before sending a batch (when batch size limit is not reached)"""

    max_in_progress: Annotated[
        Optional[float], pydantic.Field(alias="maxInProgress")
    ] = 10
    r"""The maximum number of in-progress API requests before backpressure is applied."""

    description: Optional[str] = None

    pq_strict_ordering: Annotated[
        Optional[bool], pydantic.Field(alias="pqStrictOrdering")
    ] = True
    r"""Use FIFO (first in, first out) processing. Disable to forward new events to receivers before queue is flushed."""

    pq_rate_per_sec: Annotated[
        Optional[float], pydantic.Field(alias="pqRatePerSec")
    ] = 0
    r"""Throttling rate (in events per second) to impose while writing to Destinations from PQ. Defaults to 0, which disables throttling."""

    pq_mode: Annotated[
        Annotated[Optional[PqModeOptions], PlainValidator(validate_open_enum(False))],
        pydantic.Field(alias="pqMode"),
    ] = PqModeOptions.ERROR
    r"""In Error mode, PQ writes events to the filesystem if the Destination is unavailable. In Backpressure mode, PQ writes events to the filesystem when it detects backpressure from the Destination. In Always On mode, PQ always writes events to the filesystem."""

    pq_max_buffer_size: Annotated[
        Optional[float], pydantic.Field(alias="pqMaxBufferSize")
    ] = 42
    r"""The maximum number of events to hold in memory before writing the events to disk"""

    pq_max_backpressure_sec: Annotated[
        Optional[float], pydantic.Field(alias="pqMaxBackpressureSec")
    ] = 30
    r"""How long (in seconds) to wait for backpressure to resolve before engaging the queue"""

    pq_max_file_size: Annotated[
        Optional[str], pydantic.Field(alias="pqMaxFileSize")
    ] = "1 MB"
    r"""The maximum size to store in each queue file before closing and optionally compressing (KB, MB, etc.)"""

    pq_max_size: Annotated[Optional[str], pydantic.Field(alias="pqMaxSize")] = "5GB"
    r"""The maximum disk space that the queue can consume (as an average per Worker Process) before queueing stops. Enter a numeral with units of KB, MB, etc."""

    pq_path: Annotated[Optional[str], pydantic.Field(alias="pqPath")] = (
        "$CRIBL_HOME/state/queues"
    )
    r"""The location for the persistent queue files. To this field's value, the system will append: /<worker-id>/<output-id>."""

    pq_compress: Annotated[
        Annotated[
            Optional[PqCompressOptions], PlainValidator(validate_open_enum(False))
        ],
        pydantic.Field(alias="pqCompress"),
    ] = PqCompressOptions.NONE
    r"""Codec to use to compress the persisted data"""

    pq_on_backpressure: Annotated[
        Annotated[
            Optional[PqOnBackpressureOptions], PlainValidator(validate_open_enum(False))
        ],
        pydantic.Field(alias="pqOnBackpressure"),
    ] = PqOnBackpressureOptions.BLOCK
    r"""How to handle events when the queue is exerting backpressure (full capacity or low disk). 'Block' is the same behavior as non-PQ blocking. 'Drop new data' throws away incoming data, while leaving the contents of the PQ unchanged."""

    pq_controls: Annotated[
        Optional[MetadataType], pydantic.Field(alias="pqControls")
    ] = None

    @field_serializer("on_backpressure")
    def serialize_on_backpressure(self, value):
        if isinstance(value, str):
            try:
                return models.OnBackpressureOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("google_auth_method")
    def serialize_google_auth_method(self, value):
        if isinstance(value, str):
            try:
                return models.AwsAuthenticationMethodOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("pq_mode")
    def serialize_pq_mode(self, value):
        if isinstance(value, str):
            try:
                return models.PqModeOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("pq_compress")
    def serialize_pq_compress(self, value):
        if isinstance(value, str):
            try:
                return models.PqCompressOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("pq_on_backpressure")
    def serialize_pq_on_backpressure(self, value):
        if isinstance(value, str):
            try:
                return models.PqOnBackpressureOptions(value)
            except ValueError:
                return value
        return value


class OutputGooglePubsubGooglePubsub3TypedDict(TypedDict):
    type: TypeGooglePubsubOption
    topic_name: str
    r"""ID of the topic to send events to."""
    secret: str
    r"""Select or create a stored text secret"""
    google_auth_method: NotRequired[AwsAuthenticationMethodOptions]
    r"""AWS authentication method. Choose Auto to use IAM roles."""
    id: NotRequired[str]
    r"""Unique ID for this output"""
    pipeline: NotRequired[str]
    r"""Pipeline to process data before sending out to this output"""
    system_fields: NotRequired[List[str]]
    r"""Fields to automatically add to events, such as cribl_pipe. Supports wildcards."""
    environment: NotRequired[str]
    r"""Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere."""
    streamtags: NotRequired[List[str]]
    r"""Tags for filtering and grouping in @{product}"""
    create_topic: NotRequired[bool]
    r"""If enabled, create topic if it does not exist."""
    ordered_delivery: NotRequired[bool]
    r"""If enabled, send events in the order they were added to the queue. For this to work correctly, the process receiving events must have ordering enabled."""
    region: NotRequired[str]
    r"""Region to publish messages to. Select 'default' to allow Google to auto-select the nearest region. When using ordered delivery, the selected region must be allowed by message storage policy."""
    service_account_credentials: NotRequired[str]
    r"""Contents of service account credentials (JSON keys) file downloaded from Google Cloud. To upload a file, click the upload button at this field's upper right."""
    batch_size: NotRequired[float]
    r"""The maximum number of items the Google API should batch before it sends them to the topic."""
    batch_timeout: NotRequired[float]
    r"""The maximum amount of time, in milliseconds, that the Google API should wait to send a batch (if the Batch size is not reached)."""
    max_queue_size: NotRequired[float]
    r"""Maximum number of queued batches before blocking."""
    max_record_size_kb: NotRequired[float]
    r"""Maximum size (KB) of batches to send."""
    flush_period: NotRequired[float]
    r"""Maximum time to wait before sending a batch (when batch size limit is not reached)"""
    max_in_progress: NotRequired[float]
    r"""The maximum number of in-progress API requests before backpressure is applied."""
    on_backpressure: NotRequired[OnBackpressureOptions]
    r"""How to handle events when all receivers are exerting backpressure"""
    description: NotRequired[str]
    pq_strict_ordering: NotRequired[bool]
    r"""Use FIFO (first in, first out) processing. Disable to forward new events to receivers before queue is flushed."""
    pq_rate_per_sec: NotRequired[float]
    r"""Throttling rate (in events per second) to impose while writing to Destinations from PQ. Defaults to 0, which disables throttling."""
    pq_mode: NotRequired[PqModeOptions]
    r"""In Error mode, PQ writes events to the filesystem if the Destination is unavailable. In Backpressure mode, PQ writes events to the filesystem when it detects backpressure from the Destination. In Always On mode, PQ always writes events to the filesystem."""
    pq_max_buffer_size: NotRequired[float]
    r"""The maximum number of events to hold in memory before writing the events to disk"""
    pq_max_backpressure_sec: NotRequired[float]
    r"""How long (in seconds) to wait for backpressure to resolve before engaging the queue"""
    pq_max_file_size: NotRequired[str]
    r"""The maximum size to store in each queue file before closing and optionally compressing (KB, MB, etc.)"""
    pq_max_size: NotRequired[str]
    r"""The maximum disk space that the queue can consume (as an average per Worker Process) before queueing stops. Enter a numeral with units of KB, MB, etc."""
    pq_path: NotRequired[str]
    r"""The location for the persistent queue files. To this field's value, the system will append: /<worker-id>/<output-id>."""
    pq_compress: NotRequired[PqCompressOptions]
    r"""Codec to use to compress the persisted data"""
    pq_on_backpressure: NotRequired[PqOnBackpressureOptions]
    r"""How to handle events when the queue is exerting backpressure (full capacity or low disk). 'Block' is the same behavior as non-PQ blocking. 'Drop new data' throws away incoming data, while leaving the contents of the PQ unchanged."""
    pq_controls: NotRequired[MetadataTypeTypedDict]


class OutputGooglePubsubGooglePubsub3(BaseModel):
    type: TypeGooglePubsubOption

    topic_name: Annotated[str, pydantic.Field(alias="topicName")]
    r"""ID of the topic to send events to."""

    secret: str
    r"""Select or create a stored text secret"""

    google_auth_method: Annotated[
        Annotated[
            Optional[AwsAuthenticationMethodOptions],
            PlainValidator(validate_open_enum(False)),
        ],
        pydantic.Field(alias="googleAuthMethod"),
    ] = AwsAuthenticationMethodOptions.AUTO
    r"""AWS authentication method. Choose Auto to use IAM roles."""

    id: Optional[str] = None
    r"""Unique ID for this output"""

    pipeline: Optional[str] = None
    r"""Pipeline to process data before sending out to this output"""

    system_fields: Annotated[
        Optional[List[str]], pydantic.Field(alias="systemFields")
    ] = None
    r"""Fields to automatically add to events, such as cribl_pipe. Supports wildcards."""

    environment: Optional[str] = None
    r"""Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere."""

    streamtags: Optional[List[str]] = None
    r"""Tags for filtering and grouping in @{product}"""

    create_topic: Annotated[Optional[bool], pydantic.Field(alias="createTopic")] = False
    r"""If enabled, create topic if it does not exist."""

    ordered_delivery: Annotated[
        Optional[bool], pydantic.Field(alias="orderedDelivery")
    ] = False
    r"""If enabled, send events in the order they were added to the queue. For this to work correctly, the process receiving events must have ordering enabled."""

    region: Optional[str] = None
    r"""Region to publish messages to. Select 'default' to allow Google to auto-select the nearest region. When using ordered delivery, the selected region must be allowed by message storage policy."""

    service_account_credentials: Annotated[
        Optional[str], pydantic.Field(alias="serviceAccountCredentials")
    ] = None
    r"""Contents of service account credentials (JSON keys) file downloaded from Google Cloud. To upload a file, click the upload button at this field's upper right."""

    batch_size: Annotated[Optional[float], pydantic.Field(alias="batchSize")] = 1000
    r"""The maximum number of items the Google API should batch before it sends them to the topic."""

    batch_timeout: Annotated[Optional[float], pydantic.Field(alias="batchTimeout")] = (
        100
    )
    r"""The maximum amount of time, in milliseconds, that the Google API should wait to send a batch (if the Batch size is not reached)."""

    max_queue_size: Annotated[Optional[float], pydantic.Field(alias="maxQueueSize")] = (
        100
    )
    r"""Maximum number of queued batches before blocking."""

    max_record_size_kb: Annotated[
        Optional[float], pydantic.Field(alias="maxRecordSizeKB")
    ] = 256
    r"""Maximum size (KB) of batches to send."""

    flush_period: Annotated[Optional[float], pydantic.Field(alias="flushPeriod")] = 1
    r"""Maximum time to wait before sending a batch (when batch size limit is not reached)"""

    max_in_progress: Annotated[
        Optional[float], pydantic.Field(alias="maxInProgress")
    ] = 10
    r"""The maximum number of in-progress API requests before backpressure is applied."""

    on_backpressure: Annotated[
        Annotated[
            Optional[OnBackpressureOptions], PlainValidator(validate_open_enum(False))
        ],
        pydantic.Field(alias="onBackpressure"),
    ] = OnBackpressureOptions.BLOCK
    r"""How to handle events when all receivers are exerting backpressure"""

    description: Optional[str] = None

    pq_strict_ordering: Annotated[
        Optional[bool], pydantic.Field(alias="pqStrictOrdering")
    ] = True
    r"""Use FIFO (first in, first out) processing. Disable to forward new events to receivers before queue is flushed."""

    pq_rate_per_sec: Annotated[
        Optional[float], pydantic.Field(alias="pqRatePerSec")
    ] = 0
    r"""Throttling rate (in events per second) to impose while writing to Destinations from PQ. Defaults to 0, which disables throttling."""

    pq_mode: Annotated[
        Annotated[Optional[PqModeOptions], PlainValidator(validate_open_enum(False))],
        pydantic.Field(alias="pqMode"),
    ] = PqModeOptions.ERROR
    r"""In Error mode, PQ writes events to the filesystem if the Destination is unavailable. In Backpressure mode, PQ writes events to the filesystem when it detects backpressure from the Destination. In Always On mode, PQ always writes events to the filesystem."""

    pq_max_buffer_size: Annotated[
        Optional[float], pydantic.Field(alias="pqMaxBufferSize")
    ] = 42
    r"""The maximum number of events to hold in memory before writing the events to disk"""

    pq_max_backpressure_sec: Annotated[
        Optional[float], pydantic.Field(alias="pqMaxBackpressureSec")
    ] = 30
    r"""How long (in seconds) to wait for backpressure to resolve before engaging the queue"""

    pq_max_file_size: Annotated[
        Optional[str], pydantic.Field(alias="pqMaxFileSize")
    ] = "1 MB"
    r"""The maximum size to store in each queue file before closing and optionally compressing (KB, MB, etc.)"""

    pq_max_size: Annotated[Optional[str], pydantic.Field(alias="pqMaxSize")] = "5GB"
    r"""The maximum disk space that the queue can consume (as an average per Worker Process) before queueing stops. Enter a numeral with units of KB, MB, etc."""

    pq_path: Annotated[Optional[str], pydantic.Field(alias="pqPath")] = (
        "$CRIBL_HOME/state/queues"
    )
    r"""The location for the persistent queue files. To this field's value, the system will append: /<worker-id>/<output-id>."""

    pq_compress: Annotated[
        Annotated[
            Optional[PqCompressOptions], PlainValidator(validate_open_enum(False))
        ],
        pydantic.Field(alias="pqCompress"),
    ] = PqCompressOptions.NONE
    r"""Codec to use to compress the persisted data"""

    pq_on_backpressure: Annotated[
        Annotated[
            Optional[PqOnBackpressureOptions], PlainValidator(validate_open_enum(False))
        ],
        pydantic.Field(alias="pqOnBackpressure"),
    ] = PqOnBackpressureOptions.BLOCK
    r"""How to handle events when the queue is exerting backpressure (full capacity or low disk). 'Block' is the same behavior as non-PQ blocking. 'Drop new data' throws away incoming data, while leaving the contents of the PQ unchanged."""

    pq_controls: Annotated[
        Optional[MetadataType], pydantic.Field(alias="pqControls")
    ] = None

    @field_serializer("google_auth_method")
    def serialize_google_auth_method(self, value):
        if isinstance(value, str):
            try:
                return models.AwsAuthenticationMethodOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("on_backpressure")
    def serialize_on_backpressure(self, value):
        if isinstance(value, str):
            try:
                return models.OnBackpressureOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("pq_mode")
    def serialize_pq_mode(self, value):
        if isinstance(value, str):
            try:
                return models.PqModeOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("pq_compress")
    def serialize_pq_compress(self, value):
        if isinstance(value, str):
            try:
                return models.PqCompressOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("pq_on_backpressure")
    def serialize_pq_on_backpressure(self, value):
        if isinstance(value, str):
            try:
                return models.PqOnBackpressureOptions(value)
            except ValueError:
                return value
        return value


class OutputGooglePubsubGooglePubsub2TypedDict(TypedDict):
    type: TypeGooglePubsubOption
    topic_name: str
    r"""ID of the topic to send events to."""
    service_account_credentials: str
    r"""Contents of service account credentials (JSON keys) file downloaded from Google Cloud. To upload a file, click the upload button at this field's upper right."""
    google_auth_method: NotRequired[AwsAuthenticationMethodOptions]
    r"""AWS authentication method. Choose Auto to use IAM roles."""
    id: NotRequired[str]
    r"""Unique ID for this output"""
    pipeline: NotRequired[str]
    r"""Pipeline to process data before sending out to this output"""
    system_fields: NotRequired[List[str]]
    r"""Fields to automatically add to events, such as cribl_pipe. Supports wildcards."""
    environment: NotRequired[str]
    r"""Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere."""
    streamtags: NotRequired[List[str]]
    r"""Tags for filtering and grouping in @{product}"""
    create_topic: NotRequired[bool]
    r"""If enabled, create topic if it does not exist."""
    ordered_delivery: NotRequired[bool]
    r"""If enabled, send events in the order they were added to the queue. For this to work correctly, the process receiving events must have ordering enabled."""
    region: NotRequired[str]
    r"""Region to publish messages to. Select 'default' to allow Google to auto-select the nearest region. When using ordered delivery, the selected region must be allowed by message storage policy."""
    secret: NotRequired[str]
    r"""Select or create a stored text secret"""
    batch_size: NotRequired[float]
    r"""The maximum number of items the Google API should batch before it sends them to the topic."""
    batch_timeout: NotRequired[float]
    r"""The maximum amount of time, in milliseconds, that the Google API should wait to send a batch (if the Batch size is not reached)."""
    max_queue_size: NotRequired[float]
    r"""Maximum number of queued batches before blocking."""
    max_record_size_kb: NotRequired[float]
    r"""Maximum size (KB) of batches to send."""
    flush_period: NotRequired[float]
    r"""Maximum time to wait before sending a batch (when batch size limit is not reached)"""
    max_in_progress: NotRequired[float]
    r"""The maximum number of in-progress API requests before backpressure is applied."""
    on_backpressure: NotRequired[OnBackpressureOptions]
    r"""How to handle events when all receivers are exerting backpressure"""
    description: NotRequired[str]
    pq_strict_ordering: NotRequired[bool]
    r"""Use FIFO (first in, first out) processing. Disable to forward new events to receivers before queue is flushed."""
    pq_rate_per_sec: NotRequired[float]
    r"""Throttling rate (in events per second) to impose while writing to Destinations from PQ. Defaults to 0, which disables throttling."""
    pq_mode: NotRequired[PqModeOptions]
    r"""In Error mode, PQ writes events to the filesystem if the Destination is unavailable. In Backpressure mode, PQ writes events to the filesystem when it detects backpressure from the Destination. In Always On mode, PQ always writes events to the filesystem."""
    pq_max_buffer_size: NotRequired[float]
    r"""The maximum number of events to hold in memory before writing the events to disk"""
    pq_max_backpressure_sec: NotRequired[float]
    r"""How long (in seconds) to wait for backpressure to resolve before engaging the queue"""
    pq_max_file_size: NotRequired[str]
    r"""The maximum size to store in each queue file before closing and optionally compressing (KB, MB, etc.)"""
    pq_max_size: NotRequired[str]
    r"""The maximum disk space that the queue can consume (as an average per Worker Process) before queueing stops. Enter a numeral with units of KB, MB, etc."""
    pq_path: NotRequired[str]
    r"""The location for the persistent queue files. To this field's value, the system will append: /<worker-id>/<output-id>."""
    pq_compress: NotRequired[PqCompressOptions]
    r"""Codec to use to compress the persisted data"""
    pq_on_backpressure: NotRequired[PqOnBackpressureOptions]
    r"""How to handle events when the queue is exerting backpressure (full capacity or low disk). 'Block' is the same behavior as non-PQ blocking. 'Drop new data' throws away incoming data, while leaving the contents of the PQ unchanged."""
    pq_controls: NotRequired[MetadataTypeTypedDict]


class OutputGooglePubsubGooglePubsub2(BaseModel):
    type: TypeGooglePubsubOption

    topic_name: Annotated[str, pydantic.Field(alias="topicName")]
    r"""ID of the topic to send events to."""

    service_account_credentials: Annotated[
        str, pydantic.Field(alias="serviceAccountCredentials")
    ]
    r"""Contents of service account credentials (JSON keys) file downloaded from Google Cloud. To upload a file, click the upload button at this field's upper right."""

    google_auth_method: Annotated[
        Annotated[
            Optional[AwsAuthenticationMethodOptions],
            PlainValidator(validate_open_enum(False)),
        ],
        pydantic.Field(alias="googleAuthMethod"),
    ] = AwsAuthenticationMethodOptions.AUTO
    r"""AWS authentication method. Choose Auto to use IAM roles."""

    id: Optional[str] = None
    r"""Unique ID for this output"""

    pipeline: Optional[str] = None
    r"""Pipeline to process data before sending out to this output"""

    system_fields: Annotated[
        Optional[List[str]], pydantic.Field(alias="systemFields")
    ] = None
    r"""Fields to automatically add to events, such as cribl_pipe. Supports wildcards."""

    environment: Optional[str] = None
    r"""Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere."""

    streamtags: Optional[List[str]] = None
    r"""Tags for filtering and grouping in @{product}"""

    create_topic: Annotated[Optional[bool], pydantic.Field(alias="createTopic")] = False
    r"""If enabled, create topic if it does not exist."""

    ordered_delivery: Annotated[
        Optional[bool], pydantic.Field(alias="orderedDelivery")
    ] = False
    r"""If enabled, send events in the order they were added to the queue. For this to work correctly, the process receiving events must have ordering enabled."""

    region: Optional[str] = None
    r"""Region to publish messages to. Select 'default' to allow Google to auto-select the nearest region. When using ordered delivery, the selected region must be allowed by message storage policy."""

    secret: Optional[str] = None
    r"""Select or create a stored text secret"""

    batch_size: Annotated[Optional[float], pydantic.Field(alias="batchSize")] = 1000
    r"""The maximum number of items the Google API should batch before it sends them to the topic."""

    batch_timeout: Annotated[Optional[float], pydantic.Field(alias="batchTimeout")] = (
        100
    )
    r"""The maximum amount of time, in milliseconds, that the Google API should wait to send a batch (if the Batch size is not reached)."""

    max_queue_size: Annotated[Optional[float], pydantic.Field(alias="maxQueueSize")] = (
        100
    )
    r"""Maximum number of queued batches before blocking."""

    max_record_size_kb: Annotated[
        Optional[float], pydantic.Field(alias="maxRecordSizeKB")
    ] = 256
    r"""Maximum size (KB) of batches to send."""

    flush_period: Annotated[Optional[float], pydantic.Field(alias="flushPeriod")] = 1
    r"""Maximum time to wait before sending a batch (when batch size limit is not reached)"""

    max_in_progress: Annotated[
        Optional[float], pydantic.Field(alias="maxInProgress")
    ] = 10
    r"""The maximum number of in-progress API requests before backpressure is applied."""

    on_backpressure: Annotated[
        Annotated[
            Optional[OnBackpressureOptions], PlainValidator(validate_open_enum(False))
        ],
        pydantic.Field(alias="onBackpressure"),
    ] = OnBackpressureOptions.BLOCK
    r"""How to handle events when all receivers are exerting backpressure"""

    description: Optional[str] = None

    pq_strict_ordering: Annotated[
        Optional[bool], pydantic.Field(alias="pqStrictOrdering")
    ] = True
    r"""Use FIFO (first in, first out) processing. Disable to forward new events to receivers before queue is flushed."""

    pq_rate_per_sec: Annotated[
        Optional[float], pydantic.Field(alias="pqRatePerSec")
    ] = 0
    r"""Throttling rate (in events per second) to impose while writing to Destinations from PQ. Defaults to 0, which disables throttling."""

    pq_mode: Annotated[
        Annotated[Optional[PqModeOptions], PlainValidator(validate_open_enum(False))],
        pydantic.Field(alias="pqMode"),
    ] = PqModeOptions.ERROR
    r"""In Error mode, PQ writes events to the filesystem if the Destination is unavailable. In Backpressure mode, PQ writes events to the filesystem when it detects backpressure from the Destination. In Always On mode, PQ always writes events to the filesystem."""

    pq_max_buffer_size: Annotated[
        Optional[float], pydantic.Field(alias="pqMaxBufferSize")
    ] = 42
    r"""The maximum number of events to hold in memory before writing the events to disk"""

    pq_max_backpressure_sec: Annotated[
        Optional[float], pydantic.Field(alias="pqMaxBackpressureSec")
    ] = 30
    r"""How long (in seconds) to wait for backpressure to resolve before engaging the queue"""

    pq_max_file_size: Annotated[
        Optional[str], pydantic.Field(alias="pqMaxFileSize")
    ] = "1 MB"
    r"""The maximum size to store in each queue file before closing and optionally compressing (KB, MB, etc.)"""

    pq_max_size: Annotated[Optional[str], pydantic.Field(alias="pqMaxSize")] = "5GB"
    r"""The maximum disk space that the queue can consume (as an average per Worker Process) before queueing stops. Enter a numeral with units of KB, MB, etc."""

    pq_path: Annotated[Optional[str], pydantic.Field(alias="pqPath")] = (
        "$CRIBL_HOME/state/queues"
    )
    r"""The location for the persistent queue files. To this field's value, the system will append: /<worker-id>/<output-id>."""

    pq_compress: Annotated[
        Annotated[
            Optional[PqCompressOptions], PlainValidator(validate_open_enum(False))
        ],
        pydantic.Field(alias="pqCompress"),
    ] = PqCompressOptions.NONE
    r"""Codec to use to compress the persisted data"""

    pq_on_backpressure: Annotated[
        Annotated[
            Optional[PqOnBackpressureOptions], PlainValidator(validate_open_enum(False))
        ],
        pydantic.Field(alias="pqOnBackpressure"),
    ] = PqOnBackpressureOptions.BLOCK
    r"""How to handle events when the queue is exerting backpressure (full capacity or low disk). 'Block' is the same behavior as non-PQ blocking. 'Drop new data' throws away incoming data, while leaving the contents of the PQ unchanged."""

    pq_controls: Annotated[
        Optional[MetadataType], pydantic.Field(alias="pqControls")
    ] = None

    @field_serializer("google_auth_method")
    def serialize_google_auth_method(self, value):
        if isinstance(value, str):
            try:
                return models.AwsAuthenticationMethodOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("on_backpressure")
    def serialize_on_backpressure(self, value):
        if isinstance(value, str):
            try:
                return models.OnBackpressureOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("pq_mode")
    def serialize_pq_mode(self, value):
        if isinstance(value, str):
            try:
                return models.PqModeOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("pq_compress")
    def serialize_pq_compress(self, value):
        if isinstance(value, str):
            try:
                return models.PqCompressOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("pq_on_backpressure")
    def serialize_pq_on_backpressure(self, value):
        if isinstance(value, str):
            try:
                return models.PqOnBackpressureOptions(value)
            except ValueError:
                return value
        return value


class OutputGooglePubsubGooglePubsub1TypedDict(TypedDict):
    type: TypeGooglePubsubOption
    topic_name: str
    r"""ID of the topic to send events to."""
    google_auth_method: NotRequired[AwsAuthenticationMethodOptions]
    r"""AWS authentication method. Choose Auto to use IAM roles."""
    id: NotRequired[str]
    r"""Unique ID for this output"""
    pipeline: NotRequired[str]
    r"""Pipeline to process data before sending out to this output"""
    system_fields: NotRequired[List[str]]
    r"""Fields to automatically add to events, such as cribl_pipe. Supports wildcards."""
    environment: NotRequired[str]
    r"""Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere."""
    streamtags: NotRequired[List[str]]
    r"""Tags for filtering and grouping in @{product}"""
    create_topic: NotRequired[bool]
    r"""If enabled, create topic if it does not exist."""
    ordered_delivery: NotRequired[bool]
    r"""If enabled, send events in the order they were added to the queue. For this to work correctly, the process receiving events must have ordering enabled."""
    region: NotRequired[str]
    r"""Region to publish messages to. Select 'default' to allow Google to auto-select the nearest region. When using ordered delivery, the selected region must be allowed by message storage policy."""
    service_account_credentials: NotRequired[str]
    r"""Contents of service account credentials (JSON keys) file downloaded from Google Cloud. To upload a file, click the upload button at this field's upper right."""
    secret: NotRequired[str]
    r"""Select or create a stored text secret"""
    batch_size: NotRequired[float]
    r"""The maximum number of items the Google API should batch before it sends them to the topic."""
    batch_timeout: NotRequired[float]
    r"""The maximum amount of time, in milliseconds, that the Google API should wait to send a batch (if the Batch size is not reached)."""
    max_queue_size: NotRequired[float]
    r"""Maximum number of queued batches before blocking."""
    max_record_size_kb: NotRequired[float]
    r"""Maximum size (KB) of batches to send."""
    flush_period: NotRequired[float]
    r"""Maximum time to wait before sending a batch (when batch size limit is not reached)"""
    max_in_progress: NotRequired[float]
    r"""The maximum number of in-progress API requests before backpressure is applied."""
    on_backpressure: NotRequired[OnBackpressureOptions]
    r"""How to handle events when all receivers are exerting backpressure"""
    description: NotRequired[str]
    pq_strict_ordering: NotRequired[bool]
    r"""Use FIFO (first in, first out) processing. Disable to forward new events to receivers before queue is flushed."""
    pq_rate_per_sec: NotRequired[float]
    r"""Throttling rate (in events per second) to impose while writing to Destinations from PQ. Defaults to 0, which disables throttling."""
    pq_mode: NotRequired[PqModeOptions]
    r"""In Error mode, PQ writes events to the filesystem if the Destination is unavailable. In Backpressure mode, PQ writes events to the filesystem when it detects backpressure from the Destination. In Always On mode, PQ always writes events to the filesystem."""
    pq_max_buffer_size: NotRequired[float]
    r"""The maximum number of events to hold in memory before writing the events to disk"""
    pq_max_backpressure_sec: NotRequired[float]
    r"""How long (in seconds) to wait for backpressure to resolve before engaging the queue"""
    pq_max_file_size: NotRequired[str]
    r"""The maximum size to store in each queue file before closing and optionally compressing (KB, MB, etc.)"""
    pq_max_size: NotRequired[str]
    r"""The maximum disk space that the queue can consume (as an average per Worker Process) before queueing stops. Enter a numeral with units of KB, MB, etc."""
    pq_path: NotRequired[str]
    r"""The location for the persistent queue files. To this field's value, the system will append: /<worker-id>/<output-id>."""
    pq_compress: NotRequired[PqCompressOptions]
    r"""Codec to use to compress the persisted data"""
    pq_on_backpressure: NotRequired[PqOnBackpressureOptions]
    r"""How to handle events when the queue is exerting backpressure (full capacity or low disk). 'Block' is the same behavior as non-PQ blocking. 'Drop new data' throws away incoming data, while leaving the contents of the PQ unchanged."""
    pq_controls: NotRequired[MetadataTypeTypedDict]


class OutputGooglePubsubGooglePubsub1(BaseModel):
    type: TypeGooglePubsubOption

    topic_name: Annotated[str, pydantic.Field(alias="topicName")]
    r"""ID of the topic to send events to."""

    google_auth_method: Annotated[
        Annotated[
            Optional[AwsAuthenticationMethodOptions],
            PlainValidator(validate_open_enum(False)),
        ],
        pydantic.Field(alias="googleAuthMethod"),
    ] = AwsAuthenticationMethodOptions.AUTO
    r"""AWS authentication method. Choose Auto to use IAM roles."""

    id: Optional[str] = None
    r"""Unique ID for this output"""

    pipeline: Optional[str] = None
    r"""Pipeline to process data before sending out to this output"""

    system_fields: Annotated[
        Optional[List[str]], pydantic.Field(alias="systemFields")
    ] = None
    r"""Fields to automatically add to events, such as cribl_pipe. Supports wildcards."""

    environment: Optional[str] = None
    r"""Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere."""

    streamtags: Optional[List[str]] = None
    r"""Tags for filtering and grouping in @{product}"""

    create_topic: Annotated[Optional[bool], pydantic.Field(alias="createTopic")] = False
    r"""If enabled, create topic if it does not exist."""

    ordered_delivery: Annotated[
        Optional[bool], pydantic.Field(alias="orderedDelivery")
    ] = False
    r"""If enabled, send events in the order they were added to the queue. For this to work correctly, the process receiving events must have ordering enabled."""

    region: Optional[str] = None
    r"""Region to publish messages to. Select 'default' to allow Google to auto-select the nearest region. When using ordered delivery, the selected region must be allowed by message storage policy."""

    service_account_credentials: Annotated[
        Optional[str], pydantic.Field(alias="serviceAccountCredentials")
    ] = None
    r"""Contents of service account credentials (JSON keys) file downloaded from Google Cloud. To upload a file, click the upload button at this field's upper right."""

    secret: Optional[str] = None
    r"""Select or create a stored text secret"""

    batch_size: Annotated[Optional[float], pydantic.Field(alias="batchSize")] = 1000
    r"""The maximum number of items the Google API should batch before it sends them to the topic."""

    batch_timeout: Annotated[Optional[float], pydantic.Field(alias="batchTimeout")] = (
        100
    )
    r"""The maximum amount of time, in milliseconds, that the Google API should wait to send a batch (if the Batch size is not reached)."""

    max_queue_size: Annotated[Optional[float], pydantic.Field(alias="maxQueueSize")] = (
        100
    )
    r"""Maximum number of queued batches before blocking."""

    max_record_size_kb: Annotated[
        Optional[float], pydantic.Field(alias="maxRecordSizeKB")
    ] = 256
    r"""Maximum size (KB) of batches to send."""

    flush_period: Annotated[Optional[float], pydantic.Field(alias="flushPeriod")] = 1
    r"""Maximum time to wait before sending a batch (when batch size limit is not reached)"""

    max_in_progress: Annotated[
        Optional[float], pydantic.Field(alias="maxInProgress")
    ] = 10
    r"""The maximum number of in-progress API requests before backpressure is applied."""

    on_backpressure: Annotated[
        Annotated[
            Optional[OnBackpressureOptions], PlainValidator(validate_open_enum(False))
        ],
        pydantic.Field(alias="onBackpressure"),
    ] = OnBackpressureOptions.BLOCK
    r"""How to handle events when all receivers are exerting backpressure"""

    description: Optional[str] = None

    pq_strict_ordering: Annotated[
        Optional[bool], pydantic.Field(alias="pqStrictOrdering")
    ] = True
    r"""Use FIFO (first in, first out) processing. Disable to forward new events to receivers before queue is flushed."""

    pq_rate_per_sec: Annotated[
        Optional[float], pydantic.Field(alias="pqRatePerSec")
    ] = 0
    r"""Throttling rate (in events per second) to impose while writing to Destinations from PQ. Defaults to 0, which disables throttling."""

    pq_mode: Annotated[
        Annotated[Optional[PqModeOptions], PlainValidator(validate_open_enum(False))],
        pydantic.Field(alias="pqMode"),
    ] = PqModeOptions.ERROR
    r"""In Error mode, PQ writes events to the filesystem if the Destination is unavailable. In Backpressure mode, PQ writes events to the filesystem when it detects backpressure from the Destination. In Always On mode, PQ always writes events to the filesystem."""

    pq_max_buffer_size: Annotated[
        Optional[float], pydantic.Field(alias="pqMaxBufferSize")
    ] = 42
    r"""The maximum number of events to hold in memory before writing the events to disk"""

    pq_max_backpressure_sec: Annotated[
        Optional[float], pydantic.Field(alias="pqMaxBackpressureSec")
    ] = 30
    r"""How long (in seconds) to wait for backpressure to resolve before engaging the queue"""

    pq_max_file_size: Annotated[
        Optional[str], pydantic.Field(alias="pqMaxFileSize")
    ] = "1 MB"
    r"""The maximum size to store in each queue file before closing and optionally compressing (KB, MB, etc.)"""

    pq_max_size: Annotated[Optional[str], pydantic.Field(alias="pqMaxSize")] = "5GB"
    r"""The maximum disk space that the queue can consume (as an average per Worker Process) before queueing stops. Enter a numeral with units of KB, MB, etc."""

    pq_path: Annotated[Optional[str], pydantic.Field(alias="pqPath")] = (
        "$CRIBL_HOME/state/queues"
    )
    r"""The location for the persistent queue files. To this field's value, the system will append: /<worker-id>/<output-id>."""

    pq_compress: Annotated[
        Annotated[
            Optional[PqCompressOptions], PlainValidator(validate_open_enum(False))
        ],
        pydantic.Field(alias="pqCompress"),
    ] = PqCompressOptions.NONE
    r"""Codec to use to compress the persisted data"""

    pq_on_backpressure: Annotated[
        Annotated[
            Optional[PqOnBackpressureOptions], PlainValidator(validate_open_enum(False))
        ],
        pydantic.Field(alias="pqOnBackpressure"),
    ] = PqOnBackpressureOptions.BLOCK
    r"""How to handle events when the queue is exerting backpressure (full capacity or low disk). 'Block' is the same behavior as non-PQ blocking. 'Drop new data' throws away incoming data, while leaving the contents of the PQ unchanged."""

    pq_controls: Annotated[
        Optional[MetadataType], pydantic.Field(alias="pqControls")
    ] = None

    @field_serializer("google_auth_method")
    def serialize_google_auth_method(self, value):
        if isinstance(value, str):
            try:
                return models.AwsAuthenticationMethodOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("on_backpressure")
    def serialize_on_backpressure(self, value):
        if isinstance(value, str):
            try:
                return models.OnBackpressureOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("pq_mode")
    def serialize_pq_mode(self, value):
        if isinstance(value, str):
            try:
                return models.PqModeOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("pq_compress")
    def serialize_pq_compress(self, value):
        if isinstance(value, str):
            try:
                return models.PqCompressOptions(value)
            except ValueError:
                return value
        return value

    @field_serializer("pq_on_backpressure")
    def serialize_pq_on_backpressure(self, value):
        if isinstance(value, str):
            try:
                return models.PqOnBackpressureOptions(value)
            except ValueError:
                return value
        return value


OutputGooglePubsubTypedDict = TypeAliasType(
    "OutputGooglePubsubTypedDict",
    Union[
        OutputGooglePubsubGooglePubsub1TypedDict,
        OutputGooglePubsubGooglePubsub2TypedDict,
        OutputGooglePubsubGooglePubsub3TypedDict,
        OutputGooglePubsubGooglePubsub4TypedDict,
        OutputGooglePubsubGooglePubsub5TypedDict,
    ],
)


OutputGooglePubsub = TypeAliasType(
    "OutputGooglePubsub",
    Union[
        OutputGooglePubsubGooglePubsub1,
        OutputGooglePubsubGooglePubsub2,
        OutputGooglePubsubGooglePubsub3,
        OutputGooglePubsubGooglePubsub4,
        OutputGooglePubsubGooglePubsub5,
    ],
)
