"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 1cb115a7bc49

from __future__ import annotations
from cribl_control_plane.types import BaseModel
from typing_extensions import TypedDict


class PackUninstallInfoTypedDict(TypedDict):
    id: str
    source: str


class PackUninstallInfo(BaseModel):
    id: str

    source: str
