"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
from enum import Enum
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PipelineFunctionEventstatsID(str, Enum):
    r"""Identifier of the Function. Always <code>eventstats</code>"""

    EVENTSTATS = "eventstats"


class EventstatsConfigurationTypedDict(TypedDict):
    r"""Configuration specific to the Pipeline Function."""

    aggregations: List[str]
    r"""Aggregate function(s) to perform on events. E.g., sum(bytes).where(action=='REJECT').as(TotalBytes)"""
    group_bys: NotRequired[List[str]]
    r"""Fields to group aggregates by, supports wildcard expressions."""
    max_events: NotRequired[float]
    r"""Specifies how many events are at max kept in memory to be enriched with aggregations"""
    flush_on_input_close: NotRequired[bool]
    r"""Determines if aggregations should flush when an input stream is closed. If disabled, time window settings will control flush behavior."""


class EventstatsConfiguration(BaseModel):
    r"""Configuration specific to the Pipeline Function."""

    aggregations: List[str]
    r"""Aggregate function(s) to perform on events. E.g., sum(bytes).where(action=='REJECT').as(TotalBytes)"""

    group_bys: Annotated[Optional[List[str]], pydantic.Field(alias="groupBys")] = None
    r"""Fields to group aggregates by, supports wildcard expressions."""

    max_events: Annotated[Optional[float], pydantic.Field(alias="maxEvents")] = None
    r"""Specifies how many events are at max kept in memory to be enriched with aggregations"""

    flush_on_input_close: Annotated[
        Optional[bool], pydantic.Field(alias="flushOnInputClose")
    ] = None
    r"""Determines if aggregations should flush when an input stream is closed. If disabled, time window settings will control flush behavior."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["groupBys", "maxEvents", "flushOnInputClose"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PipelineFunctionEventstatsTypedDict(TypedDict):
    id: PipelineFunctionEventstatsID
    r"""Identifier of the Function. Always <code>eventstats</code>"""
    conf: EventstatsConfigurationTypedDict
    r"""Configuration specific to the Pipeline Function."""
    filter_: NotRequired[str]
    r"""JavaScript expression that selects data to pass through the Function."""
    description: NotRequired[str]
    r"""Brief description of the Pipeline function."""
    disabled: NotRequired[bool]
    r"""If <code>true</code>, disable the Pipeline function so that events are not passed through it. Otherwise, <code>false</code>."""
    final: NotRequired[bool]
    r"""If <code>true</code>, stop passing events to downstream Pipeline Functions after the Function executes. Otherwise, <code>false</code>."""
    group_id: NotRequired[str]
    r"""Unique identifier of the group that contains the Pipeline Function."""


class PipelineFunctionEventstats(BaseModel):
    id: PipelineFunctionEventstatsID
    r"""Identifier of the Function. Always <code>eventstats</code>"""

    conf: EventstatsConfiguration
    r"""Configuration specific to the Pipeline Function."""

    filter_: Annotated[Optional[str], pydantic.Field(alias="filter")] = None
    r"""JavaScript expression that selects data to pass through the Function."""

    description: Optional[str] = None
    r"""Brief description of the Pipeline function."""

    disabled: Optional[bool] = None
    r"""If <code>true</code>, disable the Pipeline function so that events are not passed through it. Otherwise, <code>false</code>."""

    final: Optional[bool] = None
    r"""If <code>true</code>, stop passing events to downstream Pipeline Functions after the Function executes. Otherwise, <code>false</code>."""

    group_id: Annotated[Optional[str], pydantic.Field(alias="groupId")] = None
    r"""Unique identifier of the group that contains the Pipeline Function."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["filter", "description", "disabled", "final", "groupId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    EventstatsConfiguration.model_rebuild()
except NameError:
    pass
try:
    PipelineFunctionEventstats.model_rebuild()
except NameError:
    pass
