"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
from enum import Enum
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PipelineFunctionLakeExportID(str, Enum):
    r"""Identifier of the Function. Always <code>lake_export</code>"""

    LAKE_EXPORT = "lake_export"


class LakeExportConfigurationTypedDict(TypedDict):
    r"""Configuration specific to the Pipeline Function."""

    search_job_id: str
    r"""Id of the search job this function is running on."""
    dataset: str
    r"""Name of the dataset"""
    lake: NotRequired[str]
    r"""Name of the lake"""
    tee: NotRequired[bool]
    r"""Tee results to search. When set to true results will be shipped instead of stats"""
    flush_ms: NotRequired[float]
    r"""How often are stats flushed in ms"""
    suppress_previews: NotRequired[bool]
    r"""Disables generation of intermediate stats. When true stats will be emitted only on end"""


class LakeExportConfiguration(BaseModel):
    r"""Configuration specific to the Pipeline Function."""

    search_job_id: Annotated[str, pydantic.Field(alias="searchJobId")]
    r"""Id of the search job this function is running on."""

    dataset: str
    r"""Name of the dataset"""

    lake: Optional[str] = None
    r"""Name of the lake"""

    tee: Optional[bool] = None
    r"""Tee results to search. When set to true results will be shipped instead of stats"""

    flush_ms: Annotated[Optional[float], pydantic.Field(alias="flushMs")] = None
    r"""How often are stats flushed in ms"""

    suppress_previews: Annotated[
        Optional[bool], pydantic.Field(alias="suppressPreviews")
    ] = None
    r"""Disables generation of intermediate stats. When true stats will be emitted only on end"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["lake", "tee", "flushMs", "suppressPreviews"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PipelineFunctionLakeExportTypedDict(TypedDict):
    id: PipelineFunctionLakeExportID
    r"""Identifier of the Function. Always <code>lake_export</code>"""
    conf: LakeExportConfigurationTypedDict
    r"""Configuration specific to the Pipeline Function."""
    filter_: NotRequired[str]
    r"""JavaScript expression that selects data to pass through the Function."""
    description: NotRequired[str]
    r"""Brief description of the Pipeline function."""
    disabled: NotRequired[bool]
    r"""If <code>true</code>, disable the Pipeline function so that events are not passed through it. Otherwise, <code>false</code>."""
    final: NotRequired[bool]
    r"""If <code>true</code>, stop passing events to downstream Pipeline Functions after the Function executes. Otherwise, <code>false</code>."""
    group_id: NotRequired[str]
    r"""Unique identifier of the group that contains the Pipeline Function."""


class PipelineFunctionLakeExport(BaseModel):
    id: PipelineFunctionLakeExportID
    r"""Identifier of the Function. Always <code>lake_export</code>"""

    conf: LakeExportConfiguration
    r"""Configuration specific to the Pipeline Function."""

    filter_: Annotated[Optional[str], pydantic.Field(alias="filter")] = None
    r"""JavaScript expression that selects data to pass through the Function."""

    description: Optional[str] = None
    r"""Brief description of the Pipeline function."""

    disabled: Optional[bool] = None
    r"""If <code>true</code>, disable the Pipeline function so that events are not passed through it. Otherwise, <code>false</code>."""

    final: Optional[bool] = None
    r"""If <code>true</code>, stop passing events to downstream Pipeline Functions after the Function executes. Otherwise, <code>false</code>."""

    group_id: Annotated[Optional[str], pydantic.Field(alias="groupId")] = None
    r"""Unique identifier of the group that contains the Pipeline Function."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["filter", "description", "disabled", "final", "groupId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    LakeExportConfiguration.model_rebuild()
except NameError:
    pass
try:
    PipelineFunctionLakeExport.model_rebuild()
except NameError:
    pass
