"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
from enum import Enum
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PipelineFunctionStoreID(str, Enum):
    r"""Identifier of the Function. Always <code>store</code>"""

    STORE = "store"


class MappingOfFieldNamesTypedDict(TypedDict):
    r"""Mapping event property names to output field names"""


class MappingOfFieldNames(BaseModel):
    r"""Mapping event property names to output field names"""


class StoreFunctionConfigurationTypedDict(TypedDict):
    r"""Configuration specific to the Pipeline Function."""

    type: str
    r"""The type of knowledge object, generated by the function (i.e., 'lookup')"""
    destination: NotRequired[str]
    r"""Configures where and how the data should be stored"""
    description: NotRequired[str]
    r"""The knowledge object's description"""
    field_mapping: NotRequired[MappingOfFieldNamesTypedDict]
    r"""Mapping event property names to output field names"""
    separator: NotRequired[str]
    r"""Character to be used as value delimiter in output"""
    overwrite: NotRequired[bool]
    r"""For existing files, an error is thrown if overwrite is false or the file is replaced if overwrite is true"""
    compress: NotRequired[str]
    r"""True will compress output, false leaves it as it is and auto decides based on size"""
    tee: NotRequired[bool]
    r"""Tee results to the next operator"""
    max_events: NotRequired[float]
    r"""Limits how many events can be stored"""
    suppress_previews: NotRequired[bool]
    r"""Suppresses the timer-based export stats generating"""


class StoreFunctionConfiguration(BaseModel):
    r"""Configuration specific to the Pipeline Function."""

    type: str
    r"""The type of knowledge object, generated by the function (i.e., 'lookup')"""

    destination: Optional[str] = None
    r"""Configures where and how the data should be stored"""

    description: Optional[str] = None
    r"""The knowledge object's description"""

    field_mapping: Annotated[
        Optional[MappingOfFieldNames], pydantic.Field(alias="fieldMapping")
    ] = None
    r"""Mapping event property names to output field names"""

    separator: Optional[str] = None
    r"""Character to be used as value delimiter in output"""

    overwrite: Optional[bool] = None
    r"""For existing files, an error is thrown if overwrite is false or the file is replaced if overwrite is true"""

    compress: Optional[str] = None
    r"""True will compress output, false leaves it as it is and auto decides based on size"""

    tee: Optional[bool] = None
    r"""Tee results to the next operator"""

    max_events: Annotated[Optional[float], pydantic.Field(alias="maxEvents")] = None
    r"""Limits how many events can be stored"""

    suppress_previews: Annotated[
        Optional[bool], pydantic.Field(alias="suppressPreviews")
    ] = None
    r"""Suppresses the timer-based export stats generating"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "destination",
                "description",
                "fieldMapping",
                "separator",
                "overwrite",
                "compress",
                "tee",
                "maxEvents",
                "suppressPreviews",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PipelineFunctionStoreTypedDict(TypedDict):
    id: PipelineFunctionStoreID
    r"""Identifier of the Function. Always <code>store</code>"""
    conf: StoreFunctionConfigurationTypedDict
    r"""Configuration specific to the Pipeline Function."""
    filter_: NotRequired[str]
    r"""JavaScript expression that selects data to pass through the Function."""
    description: NotRequired[str]
    r"""Brief description of the Pipeline function."""
    disabled: NotRequired[bool]
    r"""If <code>true</code>, disable the Pipeline function so that events are not passed through it. Otherwise, <code>false</code>."""
    final: NotRequired[bool]
    r"""If <code>true</code>, stop passing events to downstream Pipeline Functions after the Function executes. Otherwise, <code>false</code>."""
    group_id: NotRequired[str]
    r"""Unique identifier of the group that contains the Pipeline Function."""


class PipelineFunctionStore(BaseModel):
    id: PipelineFunctionStoreID
    r"""Identifier of the Function. Always <code>store</code>"""

    conf: StoreFunctionConfiguration
    r"""Configuration specific to the Pipeline Function."""

    filter_: Annotated[Optional[str], pydantic.Field(alias="filter")] = None
    r"""JavaScript expression that selects data to pass through the Function."""

    description: Optional[str] = None
    r"""Brief description of the Pipeline function."""

    disabled: Optional[bool] = None
    r"""If <code>true</code>, disable the Pipeline function so that events are not passed through it. Otherwise, <code>false</code>."""

    final: Optional[bool] = None
    r"""If <code>true</code>, stop passing events to downstream Pipeline Functions after the Function executes. Otherwise, <code>false</code>."""

    group_id: Annotated[Optional[str], pydantic.Field(alias="groupId")] = None
    r"""Unique identifier of the group that contains the Pipeline Function."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["filter", "description", "disabled", "final", "groupId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    StoreFunctionConfiguration.model_rebuild()
except NameError:
    pass
try:
    PipelineFunctionStore.model_rebuild()
except NameError:
    pass
