"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .capturedevent import CapturedEvent, CapturedEventTypedDict
from .capturestats import CaptureStats, CaptureStatsTypedDict
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PreviewResponseTypedDict(TypedDict):
    count: float
    r"""Total count of captured events."""
    items: List[CapturedEventTypedDict]
    r"""Array of events captured during Pipeline preview."""
    stderr: str
    message: NotRequired[str]
    profile: NotRequired[str]
    stats: NotRequired[CaptureStatsTypedDict]


class PreviewResponse(BaseModel):
    count: float
    r"""Total count of captured events."""

    items: List[CapturedEvent]
    r"""Array of events captured during Pipeline preview."""

    stderr: str

    message: Optional[str] = None

    profile: Optional[str] = None

    stats: Optional[CaptureStats] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["message", "profile", "stats"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
