"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RunSettingsTypedDict(TypedDict):
    pass


class RunSettings(BaseModel):
    pass


class ScheduleTypeTypedDict(TypedDict):
    r"""Configuration for a scheduled job"""

    enabled: NotRequired[bool]
    r"""Enable to configure scheduling for this Collector"""
    skippable: NotRequired[bool]
    r"""Skippable jobs can be delayed, up to their next run time, if the system is hitting concurrency limits"""
    resume_missed: NotRequired[bool]
    r"""If Stream Leader (or single instance) restarts, run all missed jobs according to their original schedules"""
    cron_schedule: NotRequired[str]
    r"""A cron schedule on which to run this job"""
    max_concurrent_runs: NotRequired[float]
    r"""The maximum number of instances of this scheduled job that may be running at any time"""
    run: NotRequired[RunSettingsTypedDict]


class ScheduleType(BaseModel):
    r"""Configuration for a scheduled job"""

    enabled: Optional[bool] = None
    r"""Enable to configure scheduling for this Collector"""

    skippable: Optional[bool] = True
    r"""Skippable jobs can be delayed, up to their next run time, if the system is hitting concurrency limits"""

    resume_missed: Annotated[Optional[bool], pydantic.Field(alias="resumeMissed")] = (
        False
    )
    r"""If Stream Leader (or single instance) restarts, run all missed jobs according to their original schedules"""

    cron_schedule: Annotated[Optional[str], pydantic.Field(alias="cronSchedule")] = (
        "*/5 * * * *"
    )
    r"""A cron schedule on which to run this job"""

    max_concurrent_runs: Annotated[
        Optional[float], pydantic.Field(alias="maxConcurrentRuns")
    ] = 1
    r"""The maximum number of instances of this scheduled job that may be running at any time"""

    run: Optional[RunSettings] = None
