"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .maxconcurrentsearchestype import (
    MaxConcurrentSearchesType,
    MaxConcurrentSearchesTypeTypedDict,
)
from cribl_control_plane import utils
from cribl_control_plane.types import BaseModel
from cribl_control_plane.utils import validate_open_enum
from enum import Enum
import pydantic
from pydantic.functional_validators import PlainValidator
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


SearchQueueLengthTypedDict = TypeAliasType(
    "SearchQueueLengthTypedDict", Union[float, str]
)


SearchQueueLength = TypeAliasType("SearchQueueLength", Union[float, str])


class WarmPoolSizeEnum(str, Enum, metaclass=utils.OpenEnumMeta):
    AUTO = "auto"


WarmPoolSizeTypedDict = TypeAliasType(
    "WarmPoolSizeTypedDict", Union[float, WarmPoolSizeEnum]
)


WarmPoolSize = TypeAliasType(
    "WarmPoolSize",
    Union[
        float, Annotated[WarmPoolSizeEnum, PlainValidator(validate_open_enum(False))]
    ],
)


class SearchSettingsTypedDict(TypedDict):
    compress_object_cache_artifacts: bool
    field_summary_max_fields: float
    field_summary_max_nested_depth: float
    max_concurrent_searches: MaxConcurrentSearchesTypeTypedDict
    max_executors_per_search: float
    max_results_per_search: float
    max_search_duration: str
    search_history_max_jobs: float
    search_history_ttl: str
    search_queue_length: SearchQueueLengthTypedDict
    warm_pool_size: WarmPoolSizeTypedDict
    write_only_provider_secrets: bool


class SearchSettings(BaseModel):
    compress_object_cache_artifacts: Annotated[
        bool, pydantic.Field(alias="compressObjectCacheArtifacts")
    ]

    field_summary_max_fields: Annotated[
        float, pydantic.Field(alias="fieldSummaryMaxFields")
    ]

    field_summary_max_nested_depth: Annotated[
        float, pydantic.Field(alias="fieldSummaryMaxNestedDepth")
    ]

    max_concurrent_searches: Annotated[
        MaxConcurrentSearchesType, pydantic.Field(alias="maxConcurrentSearches")
    ]

    max_executors_per_search: Annotated[
        float, pydantic.Field(alias="maxExecutorsPerSearch")
    ]

    max_results_per_search: Annotated[
        float, pydantic.Field(alias="maxResultsPerSearch")
    ]

    max_search_duration: Annotated[str, pydantic.Field(alias="maxSearchDuration")]

    search_history_max_jobs: Annotated[
        float, pydantic.Field(alias="searchHistoryMaxJobs")
    ]

    search_history_ttl: Annotated[str, pydantic.Field(alias="searchHistoryTTL")]

    search_queue_length: Annotated[
        SearchQueueLength, pydantic.Field(alias="searchQueueLength")
    ]

    warm_pool_size: Annotated[WarmPoolSize, pydantic.Field(alias="warmPoolSize")]

    write_only_provider_secrets: Annotated[
        bool, pydantic.Field(alias="writeOnlyProviderSecrets")
    ]
