"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 3a268e690705

from __future__ import annotations
from cribl_control_plane import utils
from enum import Enum


class SignatureVersionOptions5(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Signature version to use for signing MinIO requests"""

    V2 = "v2"
    V4 = "v4"
