"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane import utils
from enum import Enum


class TagAfterProcessingOptions(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Whether to add a tag to each S3 object after processing."""

    FALSE = "false"
    TRUE = "true"
