"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Tags1TypeTypedDict(TypedDict):
    data_type: NotRequired[List[str]]
    domain: NotRequired[List[str]]
    streamtags: NotRequired[List[str]]
    technology: NotRequired[List[str]]


class Tags1Type(BaseModel):
    data_type: Annotated[Optional[List[str]], pydantic.Field(alias="dataType")] = None

    domain: Optional[List[str]] = None

    streamtags: Optional[List[str]] = None

    technology: Optional[List[str]] = None
