"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .emptyobject import EmptyObject, EmptyObjectTypedDict
from cribl_control_plane.types import BaseModel
import pydantic
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class TLSSettingsTypedDict(TypedDict):
    default_cipher_list: str
    default_ecdh_curve: str
    max_version: str
    min_version: str
    reject_unauthorized: bool


class TLSSettings(BaseModel):
    default_cipher_list: Annotated[str, pydantic.Field(alias="defaultCipherList")]

    default_ecdh_curve: Annotated[str, pydantic.Field(alias="defaultEcdhCurve")]

    max_version: Annotated[str, pydantic.Field(alias="maxVersion")]

    min_version: Annotated[str, pydantic.Field(alias="minVersion")]

    reject_unauthorized: Annotated[bool, pydantic.Field(alias="rejectUnauthorized")]


TLSSettingsUnionTypedDict = TypeAliasType(
    "TLSSettingsUnionTypedDict", Union[EmptyObjectTypedDict, TLSSettingsTypedDict]
)


TLSSettingsUnion = TypeAliasType("TLSSettingsUnion", Union[EmptyObject, TLSSettings])


try:
    TLSSettings.model_rebuild()
except NameError:
    pass
