"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class TypeAzureBlobOption(str, Enum):
    AZURE_BLOB = "azure_blob"
