"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .savedjobrequest import SavedJobRequest, SavedJobRequestTypedDict
from cribl_control_plane.types import BaseModel
from cribl_control_plane.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class UpdateSavedJobByIDRequestTypedDict(TypedDict):
    id_param: str
    r"""The <code>id</code> of the Collector to update."""
    saved_job_request: SavedJobRequestTypedDict
    r"""SavedJobRequest object"""


class UpdateSavedJobByIDRequest(BaseModel):
    id_param: Annotated[
        str,
        pydantic.Field(alias="id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The <code>id</code> of the Collector to update."""

    saved_job_request: Annotated[
        SavedJobRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""SavedJobRequest object"""
