name: Publish SDK (main/dev/stage/openapi-prerelease)
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - main
      - dev
      - stage
      - openapi-prerelease
    paths:
      - .speakeasy/gen.lock
  workflow_dispatch: {}

jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch-info.outputs.branch }}
      is-production: ${{ steps.branch-info.outputs.is-production }}
    steps:
      - name: Get branch information
        id: branch-info
        run: |
          echo "Current branch: ${GITHUB_REF_NAME}"
          echo "branch=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          
          # Determine if this is a production release
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "is-production=true" >> "$GITHUB_OUTPUT"
            echo "✅ Production release from main branch"
          else
            echo "is-production=false" >> "$GITHUB_OUTPUT"
            echo "✅ Prerelease from ${GITHUB_REF_NAME} branch"
          fi

  publish:
    needs: check-branch
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@1f1527d823ac3dc23f8aba805d1350024ad783fd
    with:
      target: cribl-control-plane
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      pypi_token: ${{ secrets.PYPI_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
