name: Publish Prerelease
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write

on:
  workflow_dispatch: {}

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure workflow is run from dev-remote branch
        run: |
          if [[ "${GITHUB_REF_NAME}" != "dev-remote" ]]; then
            echo "This workflow can only be run from the dev-remote branch."
            exit 1
          fi

  generate-and-push:
    needs: check-branch
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.ver.outputs.version }}
    steps:
      - name: Checkout dev-remote
        uses: actions/checkout@v4
        with:
          ref: dev-remote
          fetch-depth: 0

      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Install Speakeasy CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/speakeasy-api/speakeasy/main/install.sh | sh
          echo "$HOME/.speakeasy/bin" >> "$GITHUB_PATH"

      - name: Compute prerelease version (X.Y.Za)
        id: ver
        run: |
          BASE=$(yq '.python.version' .speakeasy/gen.yaml)
          BASE="${BASE#v}"       # strip leading v
          BASE="${BASE%%-*}"     # strip existing prerelease
          FINAL="${BASE}a"       # append 'a' for alpha
          echo "version=$FINAL" >> "$GITHUB_OUTPUT"
          echo "Computed prerelease: $FINAL"

      - name: Generate SDK
        env:
          SPEAKEASY_API_KEY: ${{ secrets.SPEAKEASY_API_KEY }}
        run: |
          speakeasy run --set-version "${{ steps.ver.outputs.version }}"

      - name: Commit and push generated changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "SyncUpBot"
          git config user.email "syncupbot@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(sdk): generate prerelease ${{ steps.ver.outputs.version }}"
            git push origin HEAD:dev-remote
          fi

  publish:
    needs: generate-and-push
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@ca0ffab4fec7166f0e60778154df8d7ec8ae3cc7
    with:
      target: cribl-control-plane
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      pypi_token:        ${{ secrets.PYPI_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
