name: Publish Prerelease
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write

on:
  workflow_dispatch: {}

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure workflow is run from dev-remote branch
        run: |
          if [[ "${GITHUB_REF_NAME}" != "dev-remote" ]]; then
            echo "This workflow can only be run from the dev-remote branch."
            exit 1
          fi

  publish:
    needs: check-branch
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@b729bcda8a0650e7faf3da46ae199cb3668f45ba
    with:
      target: cribl-control-plane
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      pypi_token:        ${{ secrets.PYPI_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
