name: Publish Prerelease SDK (alpha/beta/rc)
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write

on:
  workflow_dispatch: {}

jobs:
  generate-and-push:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.ver.outputs.version }}
    steps:
      - name: Checkout branch from workflow trigger
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Check prerelease version (X.Y.Z{a|b|rc}<n>)
        id: ver
        run: |
          VERSION=$(yq '.python.version' .speakeasy/gen.yaml)
          echo "Detected version: $VERSION"

          # Check if version is alpha, beta, or rc prerelease (Python format)
          if [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+a[0-9]+$ ]]; then
            echo "✅ Alpha prerelease version detected: $VERSION"
          elif [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+b[0-9]+$ ]]; then
            echo "✅ Beta prerelease version detected: $VERSION"
          elif [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+rc[0-9]+$ ]]; then
            echo "✅ Release candidate version detected: $VERSION"
          else
            echo "::error::Version is not a valid prerelease (expected format X.Y.Z{a|b|rc}<n>)"
            echo "::error::Detected version: $VERSION"
            echo "::error::Examples: 1.2.0a1, 1.2.0b1, 1.2.0rc1"
            exit 1
          fi

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  publish:
    needs: generate-and-push
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@57452fc95969792de6734a91400a24aeb409964c
    with:
      target: cribl-control-plane
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      pypi_token: ${{ secrets.PYPI_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
