name: Sync Main into Dev Branches

on:
  push:
    branches:
      - main

jobs:
  merge-main-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Set up Git user
        run: |
          git config user.name "SyncUpBot"
          git config user.email "syncupbot@users.noreply.github.com"

      - name: Merge main into dev-local & dev-remote
        run: |
          git fetch origin main dev-local dev-remote

          git checkout dev-local
          git merge origin/main -X theirs --no-edit
          git push origin dev-local

          git checkout dev-remote
          git reset --hard origin/main

          yq -i --indent 4 '.sources["Cribl API Reference"].inputs[0].location = "https://raw.githubusercontent.com/criblio/cribl-openapi-spec/main/specs/control-plane-prerelease.yml"' .speakeasy/workflow.yaml
          git commit -am "dev-remote: use local OpenAPI source (./openapi.yml) in workflow.yaml"

          git push origin -f dev-remote
